import { db, institutionsTable } from "@workspace/db";

// ─────────────────────────────────────────────────────────────────────────────
// UK Universities & Colleges — comprehensive addition
// Idempotent: skips any institution already present by name
// ─────────────────────────────────────────────────────────────────────────────

const UNIVERSITIES = [
  // ── SCOTLAND ────────────────────────────────────────────────────────────────
  {
    name: "University of Aberdeen", type: "University" as const, region: "Scotland", city: "Aberdeen",
    description: "One of Scotland's ancient universities (est. 1495), the University of Aberdeen is a world-leading research institution with strengths in medicine, law, energy and divinity, set on a stunning granite campus in the Granite City.",
    websiteUrl: "https://www.abdn.ac.uk", russellGroup: false, ranking: 27,
    entryRequirements: "AAB at A-level; BBBB at Scottish Highers. Strong emphasis on breadth.", ucasPoints: 136,
    studentSatisfaction: 4.1,
    notableSubjects: ["Medicine", "Law", "Divinity", "Geology", "Marine Biology"],
    facilities: ["King's College historic campus", "Sir Duncan Rice Library", "Rowett Institute", "Sports Union"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 19800,
    openDayDates: ["2026-06-06", "2026-09-19"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Edinburgh Napier University", type: "University" as const, region: "Scotland", city: "Edinburgh",
    description: "Edinburgh Napier is a modern university focused on producing career-ready graduates, with strong links to industry in business, computing, engineering and health professions across three Edinburgh campuses.",
    websiteUrl: "https://www.napier.ac.uk", russellGroup: false, ranking: 71,
    entryRequirements: "BCC at A-level; BBC at Scottish Highers. Entry requirements vary by course.", ucasPoints: 112,
    studentSatisfaction: 4.0,
    notableSubjects: ["Computing", "Business", "Engineering", "Nursing", "Film & TV"],
    facilities: ["Craiglockhart campus", "Merchiston campus", "Sighthill campus", "Innovation Quarter"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16500,
    openDayDates: ["2026-06-13", "2026-11-07"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Glasgow Caledonian University", type: "University" as const, region: "Scotland", city: "Glasgow",
    description: "Glasgow Caledonian University is a distinctive modern university with a social mission, offering applied degrees in nursing, business, engineering, computing and the life sciences. It has a campus in London too.",
    websiteUrl: "https://www.gcu.ac.uk", russellGroup: false, ranking: 74,
    entryRequirements: "BBC at A-level; BBC at Scottish Highers. Some programmes require specific subjects.", ucasPoints: 112,
    studentSatisfaction: 4.0,
    notableSubjects: ["Nursing", "Physiotherapy", "Business Management", "Computer Science", "Fashion"],
    facilities: ["City campus Glasgow", "GCU London", "The Caledonian Bar", "Student Association"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15800,
    openDayDates: ["2026-06-20", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Heriot-Watt University", type: "University" as const, region: "Scotland", city: "Edinburgh",
    description: "Heriot-Watt is a world-leading research university specialising in science, engineering, design and business, with campuses in Edinburgh, Orkney, Dubai and Malaysia — making it a truly international institution.",
    websiteUrl: "https://www.hw.ac.uk", russellGroup: false, ranking: 29,
    entryRequirements: "ABB at A-level; ABBB at Scottish Highers. Strong Maths/Science requirement for STEM.", ucasPoints: 128,
    studentSatisfaction: 4.1,
    notableSubjects: ["Engineering", "Actuarial Science", "Architecture", "Computer Science", "International Business"],
    facilities: ["Edinburgh campus", "Dubai campus", "Malaysia campus", "National Robotarium", "Research Park"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 19000,
    openDayDates: ["2026-05-30", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Queen Margaret University", type: "University" as const, region: "Scotland", city: "Edinburgh",
    description: "Queen Margaret University is a specialist teaching-led university focused on health sciences, business and creative arts, delivering excellent graduate employment rates from its modern campus in Musselburgh.",
    websiteUrl: "https://www.qmu.ac.uk", russellGroup: false, ranking: 88,
    entryRequirements: "BCC at A-level; BCC at Scottish Highers.", ucasPoints: 104,
    studentSatisfaction: 4.2,
    notableSubjects: ["Physiotherapy", "Dietetics", "Podiatry", "Drama", "Business"],
    facilities: ["Musselburgh campus", "Clinical skills suite", "Drama studios", "Sports facilities"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Robert Gordon University", type: "University" as const, region: "Scotland", city: "Aberdeen",
    description: "Robert Gordon University (RGU) is ranked among the UK's top modern universities, renowned for exceptional graduate employment rates in oil & gas engineering, nursing, architecture and business.",
    websiteUrl: "https://www.rgu.ac.uk", russellGroup: false, ranking: 43,
    entryRequirements: "BBC at A-level; BBB at Scottish Highers.", ucasPoints: 120,
    studentSatisfaction: 4.2,
    notableSubjects: ["Petroleum Engineering", "Architecture", "Nursing", "Pharmacy", "Computer Science"],
    facilities: ["Garthdee campus", "Offshore engineering labs", "Architecture studios", "Pharmacy simulation suite"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16800,
    openDayDates: ["2026-05-23", "2026-09-26"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Dundee", type: "University" as const, region: "Scotland", city: "Dundee",
    description: "The University of Dundee is internationally recognised for research excellence in life sciences, medicine, dentistry, law and art & design. Its Ninewells medical campus is one of Europe's largest teaching hospitals.",
    websiteUrl: "https://www.dundee.ac.uk", russellGroup: false, ranking: 26,
    entryRequirements: "ABB at A-level; ABBB at Scottish Highers. Medicine requires AAA.", ucasPoints: 136,
    studentSatisfaction: 4.2,
    notableSubjects: ["Medicine", "Dentistry", "Law", "Game Design", "Life Sciences"],
    facilities: ["Ninewells Hospital campus", "Duncan of Jordanstone Art College", "Sports & Wellbeing Park"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 20500,
    openDayDates: ["2026-06-13", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Abertay University", type: "University" as const, region: "Scotland", city: "Dundee",
    description: "Abertay University is a specialist university in Dundee best known for pioneering the world's first video game degree and sustaining Scotland's booming games development sector alongside food & biosciences and cybersecurity.",
    websiteUrl: "https://www.abertay.ac.uk", russellGroup: false, ranking: 90,
    entryRequirements: "BCC at A-level; BCC at Scottish Highers.", ucasPoints: 104,
    studentSatisfaction: 4.1,
    notableSubjects: ["Computer Games Technology", "Ethical Hacking", "Food & Nutrition", "Psychology", "Environmental Science"],
    facilities: ["City centre campus", "High-performance computing lab", "Games lab", "Sensory evaluation suite"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-06", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Stirling", type: "University" as const, region: "Scotland", city: "Stirling",
    description: "The University of Stirling sits on a beautiful campus beside Stirling Castle and Loch Lomond. It leads in aquaculture, nursing, sports, finance and film/media studies and has a unique semester-based academic calendar.",
    websiteUrl: "https://www.stir.ac.uk", russellGroup: false, ranking: 34,
    entryRequirements: "ABB at A-level; BBBB at Scottish Highers.", ucasPoints: 128,
    studentSatisfaction: 4.3,
    notableSubjects: ["Aquaculture", "Nursing", "Finance", "Film & Media", "Sports Studies"],
    facilities: ["Loch Lomond campus", "Macrobert Arts Centre", "Gannochy Sport Centre", "Innovation Park"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 17200,
    openDayDates: ["2026-05-16", "2026-09-19"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Strathclyde", type: "University" as const, region: "Scotland", city: "Glasgow",
    description: "Known as 'the place of useful learning', Strathclyde is a leading international technological university with outstanding engineering, business, law and science faculties based in the heart of Glasgow.",
    websiteUrl: "https://www.strath.ac.uk", russellGroup: false, ranking: 24,
    entryRequirements: "AAB at A-level; AABB at Scottish Highers. Engineering requires Maths.", ucasPoints: 136,
    studentSatisfaction: 4.2,
    notableSubjects: ["Engineering", "Business", "Law", "Pharmacy", "Computer Science"],
    facilities: ["John Anderson Campus", "Advanced Manufacturing Research Centre", "Strathclyde Business School"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 21500,
    openDayDates: ["2026-06-13", "2026-11-07"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of the Highlands and Islands (UHI)", type: "University" as const, region: "Scotland", city: "Inverness",
    description: "UHI is a unique partnership of thirteen colleges and research institutions spread across the Highlands and Islands of Scotland, offering degrees alongside vocational and professional qualifications in stunning rural settings.",
    websiteUrl: "https://www.uhi.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "Entry requirements vary widely by course and partner college. Many programmes have flexible entry.", ucasPoints: 96,
    studentSatisfaction: 4.2,
    notableSubjects: ["Archaeology", "Marine Science", "Rural & Environmental Studies", "Gaelic Language", "Tourism"],
    facilities: ["13 partner campuses", "Inverness campus hub", "Marine science vessels", "Environmental research stations"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-06", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── WALES ────────────────────────────────────────────────────────────────────
  {
    name: "Aberystwyth University", type: "University" as const, region: "Wales", city: "Aberystwyth",
    description: "Aberystwyth University is a research-led institution on the coast of Cardigan Bay, renowned for politics, international relations, law, geography and the biological sciences, with consistently high student satisfaction.",
    websiteUrl: "https://www.aber.ac.uk", russellGroup: false, ranking: 37,
    entryRequirements: "BBC at A-level; BBC at Welsh Baccalaureate pathway.", ucasPoints: 112,
    studentSatisfaction: 4.4,
    notableSubjects: ["Politics & International Relations", "Law", "Geography", "Biology", "Welsh Language"],
    facilities: ["Penglais campus", "National Library access", "Sports centre", "Arts Centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 17000,
    openDayDates: ["2026-06-20", "2026-09-26"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Bangor University", type: "University" as const, region: "Wales", city: "Bangor",
    description: "Bangor University sits between Snowdonia National Park and the Menai Strait, offering world-class research in ocean sciences, forestry, psychology, music and Welsh studies in a stunning natural setting.",
    websiteUrl: "https://www.bangor.ac.uk", russellGroup: false, ranking: 40,
    entryRequirements: "BBC at A-level.", ucasPoints: 112,
    studentSatisfaction: 4.3,
    notableSubjects: ["Ocean Sciences", "Forestry", "Psychology", "Music", "Medical Sciences"],
    facilities: ["Main Arts campus", "Marine Centre Wales", "School of Ocean Sciences", "Pontio Arts Centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16000,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Swansea University", type: "University" as const, region: "Wales", city: "Swansea",
    description: "Swansea University is a research-led institution on the shores of Swansea Bay. Its Bay Campus is one of the most spectacular in the UK, with strengths in engineering, law, science and the humanities.",
    websiteUrl: "https://www.swansea.ac.uk", russellGroup: false, ranking: 32,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.2,
    notableSubjects: ["Engineering", "Law", "Computer Science", "Economics", "Medicine"],
    facilities: ["Bay Campus", "Singleton Park campus", "Computational Foundry", "Sports Village"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 18000,
    openDayDates: ["2026-06-13", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of South Wales", type: "University" as const, region: "Wales", city: "Pontypridd",
    description: "The University of South Wales is Wales's largest university by student numbers, offering a wide range of courses across its campuses in Cardiff, Pontypridd and Newport with strong industry links.",
    websiteUrl: "https://www.southwales.ac.uk", russellGroup: false, ranking: 79,
    entryRequirements: "CCC at A-level. Flexible entry for many professional programmes.", ucasPoints: 96,
    studentSatisfaction: 4.0,
    notableSubjects: ["Policing", "Nursing", "Music Technology", "Computer Science", "Engineering"],
    facilities: ["Treforest campus", "Cardiff campus", "Newport City campus", "Automotive engineering centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-27", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Wrexham University", type: "University" as const, region: "Wales", city: "Wrexham",
    description: "Wrexham University (formerly Wrexham Glyndŵr University) is a growing teaching university in North Wales, known for its community-focused approach and courses in computing, health, business, engineering and the arts.",
    websiteUrl: "https://www.wrexham.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCD at A-level. Strong focus on widening participation.", ucasPoints: 88,
    studentSatisfaction: 4.1,
    notableSubjects: ["Computing", "Health Studies", "Business", "Creative Arts", "Engineering"],
    facilities: ["Wrexham campus", "Sports science labs", "Art studios", "Employability hub"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-06", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Wales Trinity Saint David", type: "University" as const, region: "Wales", city: "Swansea",
    description: "UWTSD is a federation of campuses in Swansea, Carmarthen and London, offering professional degrees in art & design, education, business, humanities and the humanities with a strong Welsh language focus.",
    websiteUrl: "https://www.uwtsd.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level. Some programmes have portfolio or interview requirements.", ucasPoints: 88,
    studentSatisfaction: 4.1,
    notableSubjects: ["Education", "Art & Design", "Welsh Language", "Business", "Humanities"],
    facilities: ["Swansea SA1 waterfront campus", "Carmarthen campus", "London campus", "Design studios"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13500,
    openDayDates: ["2026-06-13", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── NORTHERN IRELAND ─────────────────────────────────────────────────────────
  {
    name: "Ulster University", type: "University" as const, region: "Northern Ireland", city: "Belfast",
    description: "Ulster University is Northern Ireland's largest university with campuses in Belfast, Coleraine, Londonderry and Jordanstown, offering a wide range of courses from law and business to health and art & design.",
    websiteUrl: "https://www.ulster.ac.uk", russellGroup: false, ranking: 52,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.1,
    notableSubjects: ["Law", "Nursing", "Architecture", "Computer Science", "Business"],
    facilities: ["Belfast campus", "Coleraine campus", "Magee campus", "Jordanstown campus", "SARC arts centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 4800, internationalFees: 16000,
    openDayDates: ["2026-06-06", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── NORTH WEST ENGLAND ───────────────────────────────────────────────────────
  {
    name: "Lancaster University", type: "University" as const, region: "North West", city: "Lancaster",
    description: "Lancaster University consistently ranks among the UK's top 10 universities, celebrated for management, law, health, computing and the social sciences. Its distinctive collegiate campus offers an outstanding student experience.",
    websiteUrl: "https://www.lancaster.ac.uk", russellGroup: false, ranking: 11,
    entryRequirements: "AAB at A-level.", ucasPoints: 136,
    studentSatisfaction: 4.3,
    notableSubjects: ["Management", "Law", "Psychology", "Computer Science", "Environmental Science"],
    facilities: ["Collegiate campus", "Lancaster University Management School", "Ruskin Library", "The Storey"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 21000,
    openDayDates: ["2026-06-20", "2026-09-26"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Central Lancashire (UCLan)", type: "University" as const, region: "North West", city: "Preston",
    description: "UCLan is one of England's largest universities with over 38,000 students. It's known for journalism, health sciences, engineering, law and creative arts with a thriving city-centre campus in Preston.",
    websiteUrl: "https://www.uclan.ac.uk", russellGroup: false, ranking: 58,
    entryRequirements: "BBC at A-level.", ucasPoints: 112,
    studentSatisfaction: 4.0,
    notableSubjects: ["Journalism", "Dentistry", "Engineering", "Law", "Creative Arts"],
    facilities: ["Preston city campus", "UCLan Cyprus campus", "Forensic science suites", "Newsroom"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15500,
    openDayDates: ["2026-06-13", "2026-11-07"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Chester", type: "University" as const, region: "North West", city: "Chester",
    description: "The University of Chester is one of England's oldest higher education institutions, with a beautiful historic campus supplemented by facilities in Warrington and Birkenhead. Known for health, business and humanities.",
    websiteUrl: "https://www.chester.ac.uk", russellGroup: false, ranking: 76,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.1,
    notableSubjects: ["Nursing", "Business", "Sport", "History", "Education"],
    facilities: ["Chester campus", "Warrington campus", "Riverside Campus", "Clinical skills suite"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-27", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Cumbria", type: "University" as const, region: "North West", city: "Carlisle",
    description: "The University of Cumbria operates across Carlisle, Ambleside and London campuses, focusing on nursing, education, outdoor studies and business, and is the only university within the Lake District National Park.",
    websiteUrl: "https://www.cumbria.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level. Many programmes have vocational entry routes.", ucasPoints: 88,
    studentSatisfaction: 4.2,
    notableSubjects: ["Nursing", "Education", "Outdoor Leadership", "Social Work", "Business"],
    facilities: ["Carlisle campus", "Ambleside campus", "London campus", "Outdoor education centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-13", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Edge Hill University", type: "University" as const, region: "North West", city: "Ormskirk",
    description: "Edge Hill University has been recognised as the Times Higher Education University of the Year and maintains one of the highest student satisfaction rates in the UK, with strengths in education, health and media.",
    websiteUrl: "https://www.edgehill.ac.uk", russellGroup: false, ranking: 50,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.5,
    notableSubjects: ["Education", "Nursing", "Media", "Computer Science", "Sport"],
    facilities: ["Ormskirk campus", "Creative Edge media centre", "Medical simulation suites", "Sports facilities"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Salford", type: "University" as const, region: "North West", city: "Salford",
    description: "The University of Salford is an industry-focused university at MediaCityUK, noted for media, broadcasting, acoustics, architecture and built environment. It has strong links with the BBC, ITV and major tech companies.",
    websiteUrl: "https://www.salford.ac.uk", russellGroup: false, ranking: 63,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.0,
    notableSubjects: ["Media Production", "Acoustics", "Architecture", "Nursing", "Computer Science"],
    facilities: ["MediaCityUK campus", "TV studios", "Music studios", "Innovation hub"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15000,
    openDayDates: ["2026-05-30", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Liverpool Hope University", type: "University" as const, region: "North West", city: "Liverpool",
    description: "Liverpool Hope University is the only ecumenical university in Europe, offering a welcoming campus environment with strengths in education, humanities, business, science and the creative arts.",
    websiteUrl: "https://www.hope.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.3,
    notableSubjects: ["Education", "Theology", "Psychology", "Music", "Business"],
    facilities: ["Hope Park campus", "Creative Campus", "Sports Complex", "Arts centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-13", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Liverpool John Moores University", type: "University" as const, region: "North West", city: "Liverpool",
    description: "Liverpool John Moores University is one of the UK's top modern universities with world-class facilities for sport science, pharmacy, engineering, architecture and the creative arts, set across Liverpool city centre.",
    websiteUrl: "https://www.ljmu.ac.uk", russellGroup: false, ranking: 54,
    entryRequirements: "BBC at A-level.", ucasPoints: 112,
    studentSatisfaction: 4.1,
    notableSubjects: ["Sport Science", "Pharmacy", "Architecture", "Engineering", "Creative Arts"],
    facilities: ["Mount Pleasant campus", "Byrom Street campus", "Avril Robarts Library", "Sports Science facilities"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15800,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── YORKSHIRE ────────────────────────────────────────────────────────────────
  {
    name: "University of Bradford", type: "University" as const, region: "Yorkshire", city: "Bradford",
    description: "The University of Bradford is a research university committed to socially responsible innovation, with strengths in pharmacy, engineering, computing, management, peace studies and health sciences.",
    websiteUrl: "https://www.bradford.ac.uk", russellGroup: false, ranking: 66,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.0,
    notableSubjects: ["Pharmacy", "Engineering", "Peace Studies", "Computing", "Management"],
    facilities: ["City campus", "Faculty of Life Sciences labs", "Media centre", "The Commons"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15000,
    openDayDates: ["2026-06-13", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Huddersfield", type: "University" as const, region: "Yorkshire", city: "Huddersfield",
    description: "The University of Huddersfield is the only university in the world to have won the Times Higher Education University of the Year award twice, known for music technology, engineering, nursing and teacher training.",
    websiteUrl: "https://www.hud.ac.uk", russellGroup: false, ranking: 46,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.3,
    notableSubjects: ["Music Technology", "Engineering", "Nursing", "Pharmacy", "Teacher Training"],
    facilities: ["Central campus", "Harold Wilson Building", "Music studios", "Engineering labs"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16000,
    openDayDates: ["2026-06-20", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Hull", type: "University" as const, region: "Yorkshire", city: "Hull",
    description: "The University of Hull is a research-intensive institution in the UK City of Culture, with expertise in maritime law, climate change, chemistry, business and the creative arts. Campus-in-campus design supports student life.",
    websiteUrl: "https://www.hull.ac.uk", russellGroup: false, ranking: 57,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.1,
    notableSubjects: ["Maritime Law", "Climate Change", "Chemistry", "Politics", "Drama"],
    facilities: ["Hull city campus", "Brynmor Jones Library", "Hull York Medical School", "Student Union"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15000,
    openDayDates: ["2026-06-27", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Sheffield Hallam University", type: "University" as const, region: "Yorkshire", city: "Sheffield",
    description: "Sheffield Hallam is one of England's largest universities with a vibrant city campus, known for sport science, nursing, social work, computing, business and creative arts — all with a strong emphasis on employability.",
    websiteUrl: "https://www.shu.ac.uk", russellGroup: false, ranking: 60,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.1,
    notableSubjects: ["Sport Science", "Nursing", "Computing", "Architecture", "Social Work"],
    facilities: ["City campus", "Collegiate campus", "National Centre for Sport & Exercise Medicine", "iForge makerspace"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15500,
    openDayDates: ["2026-06-06", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Leeds Trinity University", type: "University" as const, region: "Yorkshire", city: "Leeds",
    description: "Leeds Trinity University is a small, friendly university with consistently high student satisfaction, offering courses in journalism, sport, education, business and health with a strong community feel.",
    websiteUrl: "https://www.leedstrinity.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.4,
    notableSubjects: ["Journalism", "Sport Science", "Education", "Business", "Criminology"],
    facilities: ["Horsforth campus", "Trinity Leeds Journalism Centre", "Sports Complex", "Health simulation lab"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-13", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "York St John University", type: "University" as const, region: "Yorkshire", city: "York",
    description: "York St John University is based in the heart of historic York with a strong reputation in education, sport, business, the creative arts and health — offering a personal, well-supported student experience.",
    websiteUrl: "https://www.yorksj.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.3,
    notableSubjects: ["Education", "Sport Science", "Drama", "Social Work", "Business"],
    facilities: ["York city campus", "Performance spaces", "Sport & health facilities", "London campus"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── NORTH EAST ENGLAND ───────────────────────────────────────────────────────
  {
    name: "University of Sunderland", type: "University" as const, region: "North East", city: "Sunderland",
    description: "The University of Sunderland is a modern university with campuses in Sunderland and London, offering excellent courses in nursing, pharmacy, business, engineering, media and computing with strong industry partnerships.",
    websiteUrl: "https://www.sunderland.ac.uk", russellGroup: false, ranking: 73,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.1,
    notableSubjects: ["Pharmacy", "Nursing", "Computer Science", "Business", "Media"],
    facilities: ["City campus", "St Peter's campus", "London campus", "Pharma labs"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-20", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Teesside University", type: "University" as const, region: "North East", city: "Middlesbrough",
    description: "Teesside University has won the Times Higher Education Modern University of the Year award multiple times. It excels in computer games, digital technologies, nursing, engineering and social sciences.",
    websiteUrl: "https://www.tees.ac.uk", russellGroup: false, ranking: 41,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.2,
    notableSubjects: ["Computer Games", "Digital Technologies", "Nursing", "Engineering", "Social Work"],
    facilities: ["Middlesbrough campus", "National Horizons Centre", "The Curve games lab", "Simulation suites"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15000,
    openDayDates: ["2026-06-27", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── MIDLANDS ─────────────────────────────────────────────────────────────────
  {
    name: "Aston University", type: "University" as const, region: "Midlands", city: "Birmingham",
    description: "Aston University is a dynamic technology and business university in Birmingham city centre, celebrated for exceptional graduate employment rates — consistently ranking in the top 20 for graduate prospects.",
    websiteUrl: "https://www.aston.ac.uk", russellGroup: false, ranking: 28,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.1,
    notableSubjects: ["Optometry", "Business", "Engineering", "Law", "Pharmacy"],
    facilities: ["Birmingham city campus", "Aston Business School", "Ophthalmic Research Institute", "Student Village"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 20000,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "De Montfort University", type: "University" as const, region: "Midlands", city: "Leicester",
    description: "De Montfort University (DMU) is a progressive university in Leicester city centre with leading faculties in fashion design, law, engineering, health sciences and computing, and a commitment to social justice.",
    websiteUrl: "https://www.dmu.ac.uk", russellGroup: false, ranking: 67,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.0,
    notableSubjects: ["Fashion Design", "Law", "Engineering", "Nursing", "Music Technology"],
    facilities: ["Leicester city campus", "Hugh Aston Building", "Vijay Patel Building design studios", "Gateway House"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15000,
    openDayDates: ["2026-06-13", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Derby", type: "University" as const, region: "Midlands", city: "Derby",
    description: "The University of Derby focuses on career-ready education with particular strengths in psychology, nursing, business, arts and technology. It operates across Derby, Buxton and Chesterfield campuses.",
    websiteUrl: "https://www.derby.ac.uk", russellGroup: false, ranking: 72,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.1,
    notableSubjects: ["Psychology", "Nursing", "Business", "Forensic Science", "Engineering"],
    facilities: ["Kedleston Road campus", "Markeaton Street campus", "Buxton campus", "Coding hub"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-20", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Harper Adams University", type: "University" as const, region: "Midlands", city: "Newport",
    description: "Harper Adams is the UK's leading specialist land-based university, excelling in agriculture, veterinary nursing, food science, rural business and engineering — setting graduates up for careers in food and farming.",
    websiteUrl: "https://www.harper-adams.ac.uk", russellGroup: false, ranking: 35,
    entryRequirements: "BBC at A-level including a Science for many programmes.", ucasPoints: 112,
    studentSatisfaction: 4.5,
    notableSubjects: ["Agriculture", "Veterinary Nursing", "Food Science", "Rural Business", "Engineering"],
    facilities: ["Working farm", "Veterinary clinical skills centre", "Food Innovation Centre", "Precision agriculture kit"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15500,
    openDayDates: ["2026-05-30", "2026-09-26"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Keele University", type: "University" as const, region: "Midlands", city: "Keele",
    description: "Keele University has the largest campus of any UK university by acreage, with a distinctive dual-honours structure allowing students to combine subjects. It excels in medicine, pharmacy, politics and the environmental sciences.",
    websiteUrl: "https://www.keele.ac.uk", russellGroup: false, ranking: 36,
    entryRequirements: "ABB at A-level. Medicine requires AAA with UCAT.", ucasPoints: 128,
    studentSatisfaction: 4.3,
    notableSubjects: ["Medicine", "Pharmacy", "Politics", "Law", "Geosciences"],
    facilities: ["Self-contained campus", "Keele University Hospital", "Astrophysics observatory", "SMART infrastructure lab"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 19500,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Leicester", type: "University" as const, region: "Midlands", city: "Leicester",
    description: "The University of Leicester is a Russell Group-calibre research university renowned for discovering King Richard III and for space science, genetics, criminology, law and medicine from its leafy Victoria Park campus.",
    websiteUrl: "https://www.le.ac.uk", russellGroup: false, ranking: 25,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.1,
    notableSubjects: ["Space Science", "Genetics", "Criminology", "Medicine", "Law"],
    facilities: ["Victoria Park campus", "National Space Centre partnership", "Adrian Building", "Sports centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 20000,
    openDayDates: ["2026-06-13", "2026-09-19"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Lincoln", type: "University" as const, region: "Midlands", city: "Lincoln",
    description: "The University of Lincoln is a thriving university in the cathedral city of Lincoln, noted for its award-winning architecture, engineering, business, psychology and media — and for transforming the city's waterfront.",
    websiteUrl: "https://www.lincoln.ac.uk", russellGroup: false, ranking: 44,
    entryRequirements: "BCC at A-level.", ucasPoints: 112,
    studentSatisfaction: 4.2,
    notableSubjects: ["Engineering", "Architecture", "Psychology", "Business", "Media Production"],
    facilities: ["Brayford Pool campus", "Engine Shed music venue", "Isaac Newton building", "Joseph Banks Laboratories"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15500,
    openDayDates: ["2026-06-27", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Nottingham Trent University", type: "University" as const, region: "Midlands", city: "Nottingham",
    description: "NTU is consistently ranked among England's top modern universities, with outstanding courses in architecture, fashion, law, computing, sport science and business — and one of the highest graduate employment rates in the UK.",
    websiteUrl: "https://www.ntu.ac.uk", russellGroup: false, ranking: 39,
    entryRequirements: "BBC at A-level.", ucasPoints: 112,
    studentSatisfaction: 4.1,
    notableSubjects: ["Architecture", "Fashion", "Law", "Computing", "Sport Science"],
    facilities: ["City campus", "Clifton campus", "Brackenhurst campus", "MyNTU portal ecosystem"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16000,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Staffordshire University", type: "University" as const, region: "Midlands", city: "Stoke-on-Trent",
    description: "Staffordshire University focuses on professional and career-focused education with campuses in Stoke-on-Trent, Stafford and Shrewsbury, offering courses in computing, criminology, nursing and creative arts.",
    websiteUrl: "https://www.staffs.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.0,
    notableSubjects: ["Computer Games", "Forensic Science", "Nursing", "Law", "Business"],
    facilities: ["Stoke campus", "Stafford campus", "Shrewsbury campus", "Games lab"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-13", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Northampton", type: "University" as const, region: "Midlands", city: "Northampton",
    description: "The University of Northampton occupies a brand-new Waterside campus opened in 2018 and focuses on social enterprise, business, education, health and the arts with a commitment to widening participation.",
    websiteUrl: "https://www.northampton.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.0,
    notableSubjects: ["Business", "Education", "Nursing", "Social Work", "Leather Technology"],
    facilities: ["Waterside campus", "Innovation zone", "Sports centre", "Digital workspace"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-20", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Wolverhampton", type: "University" as const, region: "Midlands", city: "Wolverhampton",
    description: "The University of Wolverhampton is committed to widening access to higher education, with strong courses in nursing, law, computer science, engineering and business across campuses in Wolverhampton, Walsall and Telford.",
    websiteUrl: "https://www.wlv.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.0,
    notableSubjects: ["Nursing", "Law", "Computer Science", "Engineering", "Business"],
    facilities: ["City campus", "Walsall campus", "Telford campus", "Fabrication lab"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13500,
    openDayDates: ["2026-06-27", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Worcester", type: "University" as const, region: "Midlands", city: "Worcester",
    description: "The University of Worcester is a rapidly growing university with strong strengths in sport science, education, business, health and the humanities, set in the beautiful county of Worcestershire.",
    websiteUrl: "https://www.worcester.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.2,
    notableSubjects: ["Sport Science", "Education", "Occupational Therapy", "Business", "Psychology"],
    facilities: ["City campus", "St John's campus", "Arena sports complex", "Hive library"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13500,
    openDayDates: ["2026-06-13", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── EAST OF ENGLAND ───────────────────────────────────────────────────────────
  {
    name: "Anglia Ruskin University", type: "University" as const, region: "East of England", city: "Cambridge",
    description: "Anglia Ruskin University (ARU) has campuses in Cambridge, Chelmsford and Peterborough and is home to globally leading research in vision science, allied health, business and engineering.",
    websiteUrl: "https://www.aru.ac.uk", russellGroup: false, ranking: 56,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.0,
    notableSubjects: ["Optometry & Vision Science", "Nursing", "Business", "Computer Science", "Music"],
    facilities: ["Cambridge campus", "Chelmsford campus", "Peterborough campus", "Vision Science labs"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-06", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of East Anglia (UEA)", type: "University" as const, region: "East of England", city: "Norwich",
    description: "UEA is a research university on its own unique campus in Norwich, acclaimed for creative writing, environmental sciences, law, medicine, international development and the biological sciences.",
    websiteUrl: "https://www.uea.ac.uk", russellGroup: false, ranking: 20,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.2,
    notableSubjects: ["Creative Writing", "Environmental Sciences", "Law", "Medicine", "International Development"],
    facilities: ["Self-contained campus", "Climatic Research Unit", "LCR music venue", "Sainsbury Centre for Visual Arts"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 19000,
    openDayDates: ["2026-06-20", "2026-09-26"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Essex", type: "University" as const, region: "East of England", city: "Colchester",
    description: "The University of Essex is a research-intensive university known globally for politics, human rights, sociology, data science, economics and psycholinguistics — and consistently ranked in the top 30 for research quality.",
    websiteUrl: "https://www.essex.ac.uk", russellGroup: false, ranking: 30,
    entryRequirements: "ABB at A-level.", ucasPoints: 120,
    studentSatisfaction: 4.1,
    notableSubjects: ["Politics", "Human Rights", "Sociology", "Data Science", "Economics"],
    facilities: ["Colchester campus", "Southend campus", "Loughton campus", "Human Rights Centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 18500,
    openDayDates: ["2026-06-13", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Norwich University of the Arts (NUA)", type: "University" as const, region: "East of England", city: "Norwich",
    description: "Norwich University of the Arts is a specialist creative arts institution in the heart of Norwich, offering degrees in fine art, graphic design, fashion, film and animation in a highly studio-focused environment.",
    websiteUrl: "https://www.nua.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "Portfolio + CCC at A-level. Foundation year available.", ucasPoints: 96,
    studentSatisfaction: 4.2,
    notableSubjects: ["Fine Art", "Graphic Design", "Fashion", "Film", "Animation"],
    facilities: ["City centre campus", "Open-access print room", "Animation suites", "Photography darkrooms"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-06", "2026-11-14"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Suffolk", type: "University" as const, region: "East of England", city: "Ipswich",
    description: "University of Suffolk is a young university on Ipswich's waterfront, offering courses in nursing, education, computing, business and the creative arts with strong links to local employers across the region.",
    websiteUrl: "https://www.uos.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.2,
    notableSubjects: ["Nursing", "Education", "Computing", "Business", "Creative Arts"],
    facilities: ["Ipswich waterfront campus", "Simulation suites", "Digital labs", "Student hub"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-13", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── SOUTH EAST ENGLAND ───────────────────────────────────────────────────────
  {
    name: "University of Bath", type: "University" as const, region: "South West", city: "Bath",
    description: "The University of Bath consistently places in the UK top 10, with particular strengths in engineering, science, management, pharmacy and sport — and produces some of the highest-earning graduates in the country.",
    websiteUrl: "https://www.bath.ac.uk", russellGroup: false, ranking: 10,
    entryRequirements: "AAA at A-level. Many programmes include a placement year.", ucasPoints: 144,
    studentSatisfaction: 4.3,
    notableSubjects: ["Engineering", "Management", "Pharmacy", "Physics", "Sport Science"],
    facilities: ["Claverton Down campus", "Sports Training Village", "Institute for Policy Research", "Innovation Centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 22500,
    openDayDates: ["2026-06-06", "2026-09-19"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Brighton", type: "University" as const, region: "South East", city: "Brighton",
    description: "The University of Brighton has campuses along the Sussex coast, known for strong performance in nursing, architecture, sport science, computing and the arts — with outstanding links to Brighton's creative industries.",
    websiteUrl: "https://www.brighton.ac.uk", russellGroup: false, ranking: 69,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.0,
    notableSubjects: ["Nursing", "Architecture", "Sport Science", "Computing", "Fine Art"],
    facilities: ["Moulsecoomb campus", "Grand Parade campus", "Eastbourne campus", "Falmer sports facilities"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15000,
    openDayDates: ["2026-06-27", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Buckinghamshire New University", type: "University" as const, region: "South East", city: "High Wycombe",
    description: "Bucks New University offers professional, vocational and creative degrees across campuses in High Wycombe, Uxbridge and Aylesbury, known for aviation, nursing, creative arts and business management.",
    websiteUrl: "https://www.bucks.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.0,
    notableSubjects: ["Aviation", "Nursing", "Interior Design", "Business", "Criminology"],
    facilities: ["High Wycombe campus", "Uxbridge campus", "Flight simulation suites", "Interior design studios"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-20", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Canterbury Christ Church University", type: "University" as const, region: "South East", city: "Canterbury",
    description: "Canterbury Christ Church University is a practice-focused university with campuses across Kent, offering leading programmes in education, nursing, physiotherapy, social work and the arts in historic cathedral surroundings.",
    websiteUrl: "https://www.canterbury.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.2,
    notableSubjects: ["Education", "Nursing", "Physiotherapy", "Social Work", "Music"],
    facilities: ["Canterbury campus", "Medway campus", "Broadstairs campus", "Clinical skills lab"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-13", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Chichester", type: "University" as const, region: "South East", city: "Chichester",
    description: "The University of Chichester is a specialist teaching university excelling in sport, dance, music, education and business with two campuses in the South Downs National Park area and consistently high student satisfaction.",
    websiteUrl: "https://www.chi.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.4,
    notableSubjects: ["Sport Science", "Dance", "Music", "Education", "Business"],
    facilities: ["Chichester campus", "Bognor Regis campus", "Sport Chichester", "Music studios"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-20", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Hertfordshire", type: "University" as const, region: "South East", city: "Hatfield",
    description: "The University of Hertfordshire is a thriving modern university near London, known for aerospace engineering, pharmacy, nursing, business and computer science, with one of the best student environments in the UK.",
    websiteUrl: "https://www.herts.ac.uk", russellGroup: false, ranking: 61,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.1,
    notableSubjects: ["Aerospace Engineering", "Pharmacy", "Nursing", "Business", "Computer Science"],
    facilities: ["College Lane campus", "de Havilland campus", "Aerospace simulator", "Hertfordshire Sports Village"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15500,
    openDayDates: ["2026-06-06", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Kent", type: "University" as const, region: "South East", city: "Canterbury",
    description: "The University of Kent is a leading research university overlooking Canterbury Cathedral, with outstanding law, social policy, forensic science, computing and European studies programmes.",
    websiteUrl: "https://www.kent.ac.uk", russellGroup: false, ranking: 33,
    entryRequirements: "ABB at A-level.", ucasPoints: 120,
    studentSatisfaction: 4.1,
    notableSubjects: ["Law", "Social Policy", "Forensic Science", "Computing", "European Studies"],
    facilities: ["Canterbury campus", "Medway campus", "Brussels campus", "Darwin College"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 18500,
    openDayDates: ["2026-06-13", "2026-09-19"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Oxford Brookes University", type: "University" as const, region: "South East", city: "Oxford",
    description: "Oxford Brookes is one of the UK's leading modern universities, acclaimed for architecture, hospitality, biological sciences, sport and business — situated in the vibrant, world-famous city of Oxford.",
    websiteUrl: "https://www.brookes.ac.uk", russellGroup: false, ranking: 47,
    entryRequirements: "BCC at A-level.", ucasPoints: 112,
    studentSatisfaction: 4.2,
    notableSubjects: ["Architecture", "Hospitality Management", "Biological Sciences", "Sport", "Business"],
    facilities: ["Headington campus", "Wheatley campus", "Oxford Brookes Business School", "Sports Park"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16500,
    openDayDates: ["2026-06-20", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Reading", type: "University" as const, region: "South East", city: "Reading",
    description: "The University of Reading is a research-intensive university noted for meteorology (home of the UK's national weather centre), agriculture, food science, architecture, law and business in a beautiful parkland campus.",
    websiteUrl: "https://www.reading.ac.uk", russellGroup: false, ranking: 21,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.2,
    notableSubjects: ["Meteorology", "Agriculture", "Architecture", "Law", "Psychology"],
    facilities: ["Whiteknights campus", "NCAS atmospheric science centre", "Museum of English Rural Life", "Minghella Studios"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 20000,
    openDayDates: ["2026-06-13", "2026-09-26"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Royal Holloway, University of London", type: "University" as const, region: "South East", city: "Egham",
    description: "Royal Holloway is a leading research university within the University of London based in a stunning Victorian gothic campus in Egham, celebrated for music, psychology, computer science, management and the natural sciences.",
    websiteUrl: "https://www.royalholloway.ac.uk", russellGroup: false, ranking: 31,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.2,
    notableSubjects: ["Music", "Psychology", "Computer Science", "Management", "Geography"],
    facilities: ["Egham campus", "Founder's Building", "Bedford Library", "Emily Wilding Davison Building"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 20000,
    openDayDates: ["2026-06-06", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Sussex", type: "University" as const, region: "South East", city: "Brighton",
    description: "The University of Sussex is a world-class research university near Brighton, known for international development, media studies, law, neuroscience, physics and economics — with a proud history of academic radicalism.",
    websiteUrl: "https://www.sussex.ac.uk", russellGroup: false, ranking: 28,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.1,
    notableSubjects: ["International Development", "Media Studies", "Law", "Neuroscience", "Physics"],
    facilities: ["Falmer campus", "Freeman Centre", "Life Sciences building", "Arts C"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 20500,
    openDayDates: ["2026-06-06", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Surrey", type: "University" as const, region: "South East", city: "Guildford",
    description: "The University of Surrey consistently achieves world top rankings for satellite engineering, veterinary medicine, hospitality, nursing and chemical engineering — and produces exceptional graduate employment outcomes.",
    websiteUrl: "https://www.surrey.ac.uk", russellGroup: false, ranking: 23,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.3,
    notableSubjects: ["Satellite Engineering", "Veterinary Medicine", "Hospitality", "Nursing", "Chemical Engineering"],
    facilities: ["Surrey Research Park", "Surrey Space Centre", "Vet School", "5G Innovation Centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 21000,
    openDayDates: ["2026-06-27", "2026-09-26"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Winchester", type: "University" as const, region: "South East", city: "Winchester",
    description: "The University of Winchester is a values-driven university with consistently top student satisfaction, excelling in education, theology, creative writing, archaeology and business in the historic city of Winchester.",
    websiteUrl: "https://www.winchester.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.4,
    notableSubjects: ["Education", "Theology", "Creative Writing", "Archaeology", "Business"],
    facilities: ["King Alfred Quarter campus", "The Stripe arts venue", "Sports Pavilion", "Heritage research centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13500,
    openDayDates: ["2026-06-13", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of the Creative Arts (UCA)", type: "University" as const, region: "South East", city: "Farnham",
    description: "The University of the Creative Arts is a specialist arts and design university with campuses across Surrey and Kent. It's one of the top-ranked creative arts institutions in the world for fine art, fashion, animation and architecture.",
    websiteUrl: "https://www.uca.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "Portfolio + CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.1,
    notableSubjects: ["Fine Art", "Fashion", "Animation", "Architecture", "Graphic Design"],
    facilities: ["Farnham campus", "Canterbury campus", "Epsom campus", "Rochester campus", "Digital fabrication labs"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-06", "2026-11-07"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── SOUTH WEST ENGLAND ───────────────────────────────────────────────────────
  {
    name: "Bath Spa University", type: "University" as const, region: "South West", city: "Bath",
    description: "Bath Spa University is a creative and liberal arts university set in stunning countryside near Bath, excelling in creative writing, music, art, fashion and education with exceptional student satisfaction scores.",
    websiteUrl: "https://www.bathspa.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.4,
    notableSubjects: ["Creative Writing", "Music", "Art & Design", "Fashion", "Education"],
    facilities: ["Newton Park campus", "Locksbrook campus", "Design studios", "Recording studios"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-20", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Falmouth University", type: "University" as const, region: "South West", city: "Falmouth",
    description: "Falmouth University is a specialist creative arts university in Cornwall, ranked among the world's top art and design institutions. It covers graphic design, illustration, games, film, music and the performing arts.",
    websiteUrl: "https://www.falmouth.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "Portfolio + BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.3,
    notableSubjects: ["Graphic Design", "Illustration", "Computer Games", "Film", "Music"],
    facilities: ["Falmouth campus", "Penryn campus", "Launchpad innovation centre", "Studios"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-06", "2026-11-14"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Gloucestershire", type: "University" as const, region: "South West", city: "Cheltenham",
    description: "The University of Gloucestershire has campuses across Cheltenham and Gloucester, known for sport science, business, education, media and the natural and social sciences — with a strong focus on sustainability.",
    websiteUrl: "https://www.glos.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.2,
    notableSubjects: ["Sport Science", "Business", "Education", "Media", "Natural Sciences"],
    facilities: ["Cheltenham campus", "Gloucester campus", "Sport & Active Life centre", "The Park"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13500,
    openDayDates: ["2026-06-13", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Hartpury University", type: "University" as const, region: "South West", city: "Gloucester",
    description: "Hartpury University is a specialist higher education institution for sport, equine studies, agriculture and veterinary nursing, with world-class facilities including a working farm and elite sports centre.",
    websiteUrl: "https://www.hartpury.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.4,
    notableSubjects: ["Sport Science", "Equine Science", "Agriculture", "Veterinary Nursing", "Physiotherapy"],
    facilities: ["Hartpury campus", "Working farm", "Equestrian centre", "Elite sport facilities", "Veterinary clinic"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-05-30", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Plymouth", type: "University" as const, region: "South West", city: "Plymouth",
    description: "The University of Plymouth is the south-west's largest university, with particular strengths in marine sciences, nursing, architecture, business and the arts — and an internationally acclaimed marine institute.",
    websiteUrl: "https://www.plymouth.ac.uk", russellGroup: false, ranking: 53,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.1,
    notableSubjects: ["Marine Sciences", "Nursing", "Architecture", "Business", "Psychology"],
    facilities: ["Plymouth campus", "Marine Institute", "RNLI research partnership", "Digital fabrication labs"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16500,
    openDayDates: ["2026-06-06", "2026-09-26"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of the West of England (UWE Bristol)", type: "University" as const, region: "South West", city: "Bristol",
    description: "UWE Bristol is one of England's most popular universities, delivering career-focused degrees in engineering, law, nursing, architecture and the creative arts — with world-class facilities on its vibrant Frenchay campus.",
    websiteUrl: "https://www.uwe.ac.uk", russellGroup: false, ranking: 59,
    entryRequirements: "BBC at A-level.", ucasPoints: 112,
    studentSatisfaction: 4.1,
    notableSubjects: ["Engineering", "Law", "Nursing", "Architecture", "Creative Arts"],
    facilities: ["Frenchay campus", "Glenside campus", "City campus", "National Composites Centre partnership"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16000,
    openDayDates: ["2026-06-13", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  // ── LONDON ───────────────────────────────────────────────────────────────────
  {
    name: "Brunel University London", type: "University" as const, region: "London", city: "Uxbridge",
    description: "Brunel University London is a dynamic, research-intensive institution in West London, highly regarded for engineering, design, business, law, social sciences and sports science, with a focus on applied research.",
    websiteUrl: "https://www.brunel.ac.uk", russellGroup: false, ranking: 38,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.0,
    notableSubjects: ["Engineering", "Industrial Design", "Business", "Law", "Sport Science"],
    facilities: ["Uxbridge campus", "Brunel University London Innovation Hub", "BCAST sports analysis centre"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 19500,
    openDayDates: ["2026-06-13", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "City, University of London", type: "University" as const, region: "London", city: "London",
    description: "City, University of London is a leading institution based in the heart of the City, with outstanding law, business, journalism, optometry, engineering and health programmes and an elite Cass Business School.",
    websiteUrl: "https://www.city.ac.uk", russellGroup: false, ranking: 22,
    entryRequirements: "ABB at A-level.", ucasPoints: 128,
    studentSatisfaction: 4.0,
    notableSubjects: ["Law", "Business", "Journalism", "Optometry", "Engineering"],
    facilities: ["Northampton Square campus", "Bayes Business School", "City Law School", "Clinical simulation facilities"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 21000,
    openDayDates: ["2026-06-06", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Kingston University", type: "University" as const, region: "London", city: "Kingston upon Thames",
    description: "Kingston University is a modern university in South West London known for nursing, architecture, business, computer games and fashion — and for one of the most diverse student bodies in the UK.",
    websiteUrl: "https://www.kingston.ac.uk", russellGroup: false, ranking: 65,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.0,
    notableSubjects: ["Nursing", "Architecture", "Business", "Computer Games", "Fashion"],
    facilities: ["Penrhyn Road campus", "Kingston Hill campus", "Knights Park campus", "Town House"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 15000,
    openDayDates: ["2026-06-20", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "London Metropolitan University", type: "University" as const, region: "London", city: "London",
    description: "London Metropolitan University is one of the most diverse universities in the world, located in North London, with strengths in law, business, IT, social sciences, architecture and health sciences.",
    websiteUrl: "https://www.londonmet.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.0,
    notableSubjects: ["Law", "Business", "IT", "Architecture", "Social Sciences"],
    facilities: ["Holloway campus", "Aldgate campus", "The Graduate Centre", "Fabrication Lab"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-13", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "London South Bank University", type: "University" as const, region: "London", city: "London",
    description: "London South Bank University (LSBU) is a practice-focused university in Elephant & Castle with particular strengths in engineering, nursing, business, computing and the built environment.",
    websiteUrl: "https://www.lsbu.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.0,
    notableSubjects: ["Engineering", "Nursing", "Business", "Computing", "Architecture"],
    facilities: ["Southwark campus", "Havering campus", "Centre for Additive Manufacturing", "Clinical labs"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-06", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Middlesex University", type: "University" as const, region: "London", city: "London",
    description: "Middlesex University is a vibrant, global university in North London with campuses in Dubai and Mauritius, offering leading courses in nursing, law, business, computing and the arts.",
    websiteUrl: "https://www.mdx.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.0,
    notableSubjects: ["Nursing", "Law", "Business", "Computing", "Fine Art"],
    facilities: ["Hendon campus", "Dubai campus", "Mauritius campus", "Art & Design studio"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14500,
    openDayDates: ["2026-06-20", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of East London", type: "University" as const, region: "London", city: "London",
    description: "UEL is a dynamic east London university on a stunning Royal Docks campus, known for psychology, criminology, architecture, sport and business — and committed to widening participation and social mobility.",
    websiteUrl: "https://www.uel.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.1,
    notableSubjects: ["Psychology", "Criminology", "Architecture", "Sport Science", "Business"],
    facilities: ["Docklands campus", "Stratford campus", "Stadium Island campus", "UEL Sports Dock"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-13", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Roehampton", type: "University" as const, region: "London", city: "London",
    description: "The University of Roehampton is a collegiate university in leafy South West London, excelling in education, dance, psychology, biological sciences and business from a beautiful Victorian campus.",
    websiteUrl: "https://www.roehampton.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 96,
    studentSatisfaction: 4.1,
    notableSubjects: ["Education", "Dance", "Psychology", "Biological Sciences", "Business"],
    facilities: ["Roehampton campus", "Digby Stuart College", "Froebel College", "Parkstead House"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-20", "2026-10-17"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of West London", type: "University" as const, region: "London", city: "London",
    description: "The University of West London is consistently ranked the UK's top modern university for graduate employment, with outstanding courses in nursing, business aviation, music and hospitality management.",
    websiteUrl: "https://www.uwl.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.2,
    notableSubjects: ["Nursing", "Business Aviation", "Music", "Hospitality", "Engineering"],
    facilities: ["Ealing campus", "Brentford campus", "Reading campus", "Wembley campus", "Recording studios"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 14000,
    openDayDates: ["2026-06-06", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Westminster", type: "University" as const, region: "London", city: "London",
    description: "The University of Westminster is a globally connected, practice-focused London university, renowned for architecture, law, media, business and fashion — with teaching spaces just minutes from Oxford Street.",
    websiteUrl: "https://www.westminster.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "BCC at A-level.", ucasPoints: 104,
    studentSatisfaction: 4.0,
    notableSubjects: ["Architecture", "Law", "Media", "Fashion", "Business"],
    facilities: ["Regent Street campus", "Marylebone campus", "Harrow campus", "Cavendish campus"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 16000,
    openDayDates: ["2026-06-13", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of St Andrews", type: "University" as const, region: "Scotland", city: "St Andrews",
    description: "The University of St Andrews is Scotland's oldest university (est. 1413) and consistently one of the UK's top 3, renowned for philosophy, English, physics, mathematics, international relations and medicine.",
    websiteUrl: "https://www.st-andrews.ac.uk", russellGroup: false, ranking: 3,
    entryRequirements: "AAA at A-level. Some programmes require AAA+A.", ucasPoints: 152,
    studentSatisfaction: 4.4,
    notableSubjects: ["Philosophy", "English", "Physics", "Mathematics", "International Relations"],
    facilities: ["Historic town campus", "North Haugh science campus", "St Andrews Links Golf", "Bell Pettigrew Museum"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 26000,
    openDayDates: ["2026-09-12", "2026-11-07"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "University of Bedfordshire", type: "University" as const, region: "East of England", city: "Luton",
    description: "The University of Bedfordshire offers an accessible, career-focused university education across campuses in Luton and Bedford, with strengths in nursing, business, media and sport.",
    websiteUrl: "https://www.beds.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.0,
    notableSubjects: ["Nursing", "Business", "Media", "Sport Science", "Education"],
    facilities: ["Luton campus", "Bedford campus", "Media arts centre", "Centre for Sport Science"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-27", "2026-10-03"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Open University", type: "University" as const, region: "Midlands", city: "Milton Keynes",
    description: "The Open University is the world's leading distance learning university, enabling anyone to study for a degree flexibly around work and life. It offers over 400 qualifications and has 3 million alumni worldwide.",
    websiteUrl: "https://www.open.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "Open entry — no prior qualifications required. Modules stackable to degree level.", ucasPoints: null,
    studentSatisfaction: 4.3,
    notableSubjects: ["Psychology", "Business", "Computing", "Health Sciences", "Law"],
    facilities: ["Walton Hall campus (admin)", "Online learning platform", "Study groups nationwide", "Virtual labs"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 6192, internationalFees: 12000,
    openDayDates: ["2026-06-06", "2026-10-10"],
    applicationDeadline: "Rolling intake", applicationsOpen: "Throughout the year",
  },
  {
    name: "Newman University", type: "University" as const, region: "Midlands", city: "Birmingham",
    description: "Newman University is a small, values-led Catholic university in Birmingham with a warm community atmosphere and strong programmes in education, sport, business and social sciences.",
    websiteUrl: "https://www.newman.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.4,
    notableSubjects: ["Education", "Sport Science", "Business", "Social Sciences", "Theology"],
    facilities: ["Bartley Green campus", "Sports centre", "Library resource centre", "Chapel"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-20", "2026-10-24"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
  {
    name: "Bishop Grosseteste University", type: "University" as const, region: "Midlands", city: "Lincoln",
    description: "Bishop Grosseteste University is a small, welcoming institution in Lincoln with a strong focus on education, humanities, business and sport. It has very high student satisfaction and is known for its community feel.",
    websiteUrl: "https://www.bishopg.ac.uk", russellGroup: false, ranking: null,
    entryRequirements: "CCC at A-level.", ucasPoints: 88,
    studentSatisfaction: 4.5,
    notableSubjects: ["Education", "English", "History", "Sport", "Business"],
    facilities: ["Lincoln campus", "Historic grounds", "Library", "Sport facilities"],
    bursaries: true, internationalStudents: true, relatedCareers: [] as number[],
    annualFees: 9250, internationalFees: 13000,
    openDayDates: ["2026-06-06", "2026-10-10"],
    applicationDeadline: "15 January 2027", applicationsOpen: "September 2026",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// FE COLLEGES
// ─────────────────────────────────────────────────────────────────────────────

const FE_COLLEGES = [
  // ── NORTH WEST ────────────────────────────────────────────────────────────────
  { name: "Blackburn College", region: "North West", city: "Blackburn" },
  { name: "Blackpool and The Fylde College", region: "North West", city: "Blackpool" },
  { name: "Bolton College", region: "North West", city: "Bolton" },
  { name: "Burnley College", region: "North West", city: "Burnley" },
  { name: "Hopwood Hall College", region: "North West", city: "Middleton" },
  { name: "Lancaster and Morecambe College", region: "North West", city: "Lancaster" },
  { name: "Lakes College", region: "North West", city: "Workington" },
  { name: "The Manchester College", region: "North West", city: "Manchester" },
  { name: "Preston's College", region: "North West", city: "Preston" },
  { name: "Runshaw College", region: "North West", city: "Leyland" },
  { name: "Salford City College", region: "North West", city: "Salford" },
  { name: "Wigan and Leigh College", region: "North West", city: "Wigan" },
  { name: "Warrington & Vale Royal College", region: "North West", city: "Warrington" },
  // ── YORKSHIRE ─────────────────────────────────────────────────────────────────
  { name: "Barnsley College", region: "Yorkshire", city: "Barnsley" },
  { name: "Bradford College", region: "Yorkshire", city: "Bradford" },
  { name: "Calderdale College", region: "Yorkshire", city: "Halifax" },
  { name: "Craven College", region: "Yorkshire", city: "Skipton" },
  { name: "Doncaster College", region: "Yorkshire", city: "Doncaster" },
  { name: "Hull College", region: "Yorkshire", city: "Hull" },
  { name: "Leeds City College", region: "Yorkshire", city: "Leeds" },
  { name: "Sheffield College", region: "Yorkshire", city: "Sheffield" },
  { name: "Thomas Rotherham College", region: "Yorkshire", city: "Rotherham" },
  { name: "Wakefield College", region: "Yorkshire", city: "Wakefield" },
  { name: "York College", region: "Yorkshire", city: "York" },
  // ── NORTH EAST ────────────────────────────────────────────────────────────────
  { name: "Gateshead College", region: "North East", city: "Gateshead" },
  { name: "Hartlepool College of Further Education", region: "North East", city: "Hartlepool" },
  { name: "Middlesbrough College", region: "North East", city: "Middlesbrough" },
  { name: "New College Durham", region: "North East", city: "Durham" },
  { name: "Sunderland College", region: "North East", city: "Sunderland" },
  { name: "Tyne Metropolitan College", region: "North East", city: "North Shields" },
  // ── MIDLANDS ──────────────────────────────────────────────────────────────────
  { name: "Burton and South Derbyshire College", region: "Midlands", city: "Burton upon Trent" },
  { name: "Derby College Group", region: "Midlands", city: "Derby" },
  { name: "Dudley College of Technology", region: "Midlands", city: "Dudley" },
  { name: "Heart of Worcestershire College", region: "Midlands", city: "Worcester" },
  { name: "Herefordshire and Ludlow College", region: "Midlands", city: "Hereford" },
  { name: "Leicester College", region: "Midlands", city: "Leicester" },
  { name: "Lincoln College", region: "Midlands", city: "Lincoln" },
  { name: "North Nottinghamshire College", region: "Midlands", city: "Worksop" },
  { name: "Nottingham College", region: "Midlands", city: "Nottingham" },
  { name: "Sandwell College", region: "Midlands", city: "West Bromwich" },
  { name: "Shrewsbury Colleges Group", region: "Midlands", city: "Shrewsbury" },
  { name: "South and City College Birmingham", region: "Midlands", city: "Birmingham" },
  { name: "Stoke-on-Trent College", region: "Midlands", city: "Stoke-on-Trent" },
  { name: "Warwickshire College Group", region: "Midlands", city: "Royal Leamington Spa" },
  { name: "Wolverhampton College", region: "Midlands", city: "Wolverhampton" },
  // ── EAST OF ENGLAND ───────────────────────────────────────────────────────────
  { name: "Cambridge Regional College", region: "East of England", city: "Cambridge" },
  { name: "Colchester Institute", region: "East of England", city: "Colchester" },
  { name: "College of West Anglia", region: "East of England", city: "King's Lynn" },
  { name: "North Hertfordshire College", region: "East of England", city: "Stevenage" },
  { name: "Peterborough College", region: "East of England", city: "Peterborough" },
  { name: "Suffolk New College", region: "East of England", city: "Ipswich" },
  // ── LONDON ────────────────────────────────────────────────────────────────────
  { name: "City of Westminster College", region: "London", city: "London" },
  { name: "Harrow College", region: "London", city: "Harrow" },
  { name: "New City College", region: "London", city: "London" },
  { name: "Richmond upon Thames College", region: "London", city: "Twickenham" },
  { name: "Uxbridge College", region: "London", city: "Uxbridge" },
  // ── SOUTH EAST ────────────────────────────────────────────────────────────────
  { name: "Chichester College Group", region: "South East", city: "Chichester" },
  { name: "East Surrey College", region: "South East", city: "Redhill" },
  { name: "Fareham College", region: "South East", city: "Fareham" },
  { name: "Farnborough College of Technology", region: "South East", city: "Farnborough" },
  { name: "Milton Keynes College", region: "South East", city: "Milton Keynes" },
  { name: "North Kent College", region: "South East", city: "Dartford" },
  { name: "Sparsholt College Hampshire", region: "South East", city: "Winchester" },
  { name: "Thanet College", region: "South East", city: "Broadstairs" },
  { name: "West Thames College", region: "South East", city: "Isleworth" },
  // ── SOUTH WEST ────────────────────────────────────────────────────────────────
  { name: "Bridgwater and Taunton College", region: "South West", city: "Bridgwater" },
  { name: "City College Plymouth", region: "South West", city: "Plymouth" },
  { name: "Exeter College", region: "South West", city: "Exeter" },
  { name: "Petroc", region: "South West", city: "Barnstaple" },
  { name: "Truro and Penwith College", region: "South West", city: "Truro" },
  { name: "Weston College", region: "South West", city: "Weston-super-Mare" },
  // ── SCOTLAND ──────────────────────────────────────────────────────────────────
  { name: "Ayrshire College", region: "Scotland", city: "Kilmarnock" },
  { name: "Borders College", region: "Scotland", city: "Galashiels" },
  { name: "City of Glasgow College", region: "Scotland", city: "Glasgow" },
  { name: "Dumfries and Galloway College", region: "Scotland", city: "Dumfries" },
  { name: "Dundee and Angus College", region: "Scotland", city: "Dundee" },
  { name: "Edinburgh College", region: "Scotland", city: "Edinburgh" },
  { name: "Fife College", region: "Scotland", city: "Kirkcaldy" },
  { name: "Glasgow Clyde College", region: "Scotland", city: "Glasgow" },
  { name: "Glasgow Kelvin College", region: "Scotland", city: "Glasgow" },
  { name: "New College Lanarkshire", region: "Scotland", city: "Motherwell" },
  { name: "North East Scotland College (NESCol)", region: "Scotland", city: "Aberdeen" },
  { name: "Perth College UHI", region: "Scotland", city: "Perth" },
  { name: "South Lanarkshire College", region: "Scotland", city: "East Kilbride" },
  { name: "West College Scotland", region: "Scotland", city: "Paisley" },
  { name: "West Lothian College", region: "Scotland", city: "Livingston" },
  // ── WALES ─────────────────────────────────────────────────────────────────────
  { name: "Bridgend College", region: "Wales", city: "Bridgend" },
  { name: "Cardiff and Vale College", region: "Wales", city: "Cardiff" },
  { name: "Coleg Cambria", region: "Wales", city: "Wrexham" },
  { name: "Coleg Sir Gâr", region: "Wales", city: "Carmarthen" },
  { name: "Gower College Swansea", region: "Wales", city: "Swansea" },
  { name: "NPTC Group", region: "Wales", city: "Neath" },
  { name: "Pembrokeshire College", region: "Wales", city: "Haverfordwest" },
  { name: "The College Merthyr Tydfil", region: "Wales", city: "Merthyr Tydfil" },
  { name: "Yale College", region: "Wales", city: "Wrexham" },
  // ── NORTHERN IRELAND ──────────────────────────────────────────────────────────
  { name: "North West Regional College", region: "Northern Ireland", city: "Londonderry" },
  { name: "Northern Regional College", region: "Northern Ireland", city: "Ballymena" },
  { name: "South Eastern Regional College", region: "Northern Ireland", city: "Bangor" },
  { name: "Southern Regional College", region: "Northern Ireland", city: "Newry" },
  { name: "South West College", region: "Northern Ireland", city: "Enniskillen" },
];

function buildCollege(c: { name: string; region: string; city: string }) {
  return {
    name: c.name,
    type: "College" as const,
    region: c.region,
    city: c.city,
    description: `${c.name} is a further education college in ${c.city} offering a broad range of Level 2 and Level 3 vocational qualifications, T Levels, A-levels, apprenticeships and higher education programmes across most subject areas.`,
    websiteUrl: `https://www.${c.name.toLowerCase().replace(/[^a-z0-9]/g, "")}.ac.uk`,
    russellGroup: false,
    ranking: null as number | null,
    entryRequirements: "Open-access for 16–18 students. Adult learners welcome. Individual programme requirements apply.",
    ucasPoints: null as number | null,
    studentSatisfaction: +(3.9 + Math.random() * 0.5).toFixed(1),
    notableSubjects: ["Business", "Computing", "Health & Social Care", "Engineering", "Creative Arts"],
    facilities: ["Modern classrooms", "Vocational workshops", "Library and study centre", "Student services"],
    bursaries: true,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null as number | null,
    internationalFees: null as number | null,
    openDayDates: ["2026-06-20", "2026-10-03"] as string[],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "From January 2026",
  };
}

const ALL_NEW_INSTITUTIONS = [
  ...UNIVERSITIES,
  ...FE_COLLEGES.map(buildCollege),
];

async function addHeFe() {
  console.log("Adding HE & FE institutions...\n");

  const existing = await db.select({ name: institutionsTable.name }).from(institutionsTable);
  const existingNames = new Set(existing.map((i) => i.name));

  const toInsert = ALL_NEW_INSTITUTIONS.filter((p) => !existingNames.has(p.name));

  if (toInsert.length === 0) {
    console.log("All institutions already exist. Nothing to add.");
    process.exit(0);
  }

  console.log(`Adding ${toInsert.length} institutions (${toInsert.filter(i => i.type === "University").length} universities, ${toInsert.filter(i => i.type === "College").length} colleges)...\n`);

  let added = 0;
  for (const inst of toInsert) {
    await db.insert(institutionsTable).values(inst);
    console.log(`  ✓ ${inst.name} [${inst.type}] — ${inst.city}, ${inst.region}`);
    added++;
  }

  console.log(`\nDone! Added ${added} institutions.`);
  process.exit(0);
}

addHeFe().catch((err) => {
  console.error("Failed:", err);
  process.exit(1);
});
