import { db } from "@workspace/db";
import { subjectsTable } from "@workspace/db/schema";

const scottishSubjects = [
  // ── National 5 subjects ────────────────────────────────────────────────────
  {
    name: "Mathematics",
    level: "National 5",
    category: "STEM",
    description: "Develops numerical, algebraic, and geometric reasoning. National 5 Mathematics is the main qualification for Scottish students aiming for Higher Mathematics and STEM university courses.",
    examBoards: ["SQA"],
    studyTips: [
      "Practise past papers from the SQA website regularly",
      "Learn to show all working — marks are awarded for method",
      "Use the SQA Understanding Standards website to see examiner comments",
      "Focus on algebra, trigonometry and statistics as they carry the most marks",
      "Use Corbettmaths and Mathsgenie for additional practice",
    ],
    keyTopics: ["Expressions & Formulae", "Relationships", "Applications", "Algebra", "Geometry & Measure", "Trigonometry", "Statistics", "Finance"],
    assessmentStructure: "Two question papers: Paper 1 (non-calculator, 50 marks) and Paper 2 (calculator, 60 marks). No coursework component.",
    usefulResources: [
      { name: "SQA Past Papers – National 5 Maths", url: "https://www.sqa.org.uk/sqa/47373.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 Maths", url: "https://www.bbc.co.uk/bitesize/subjects/zmpfb9q", type: "Website" },
      { name: "Corbettmaths – Maths Revision", url: "https://corbettmaths.com", type: "Practice Questions" },
      { name: "Mathsgenie – Revision & Practice", url: "https://www.mathsgenie.co.uk", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "English",
    level: "National 5",
    category: "Humanities",
    description: "Develops reading, writing, talking and listening skills through engagement with Scottish and wider literature, media and language. Central to virtually every university and college course.",
    examBoards: ["SQA"],
    studyTips: [
      "Read widely — Scottish literature, modern fiction, and non-fiction",
      "Practise your essay structure: introduction, PEEL paragraphs, conclusion",
      "Learn key literary techniques (imagery, word choice, structure, tone)",
      "Practise the Reading for UA (Understanding, Analysis, Evaluation) questions",
      "Record yourself speaking to improve your Spoken Language assessment",
    ],
    keyTopics: ["Reading for Understanding, Analysis and Evaluation", "Critical Essay", "Portfolio Writing", "Spoken Language", "Literary Techniques", "Scottish Texts"],
    assessmentStructure: "Two exam papers: Reading for UAA (1 hour) and Critical Essay (1h 30m). Portfolio of writing submitted to SQA (30% of overall mark).",
    usefulResources: [
      { name: "SQA Past Papers – National 5 English", url: "https://www.sqa.org.uk/sqa/47372.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 English", url: "https://www.bbc.co.uk/bitesize/subjects/z3mpmfr", type: "Website" },
      { name: "Study Rocket – N5 English Notes", url: "https://studyrocket.co.uk", type: "Revision Guide" },
    ],
    relatedCareers: [],
  },
  {
    name: "Biology",
    level: "National 5",
    category: "STEM",
    description: "Covers cell biology, multicellular organisms, life on Earth, and the biology of chromosomes and inheritance. A gateway to medicine, nursing, and life sciences.",
    examBoards: ["SQA"],
    studyTips: [
      "Draw and label diagrams — they are frequently examined",
      "Learn the key definitions precisely",
      "Practise applying knowledge to unfamiliar biological contexts",
      "Use the SQA course specification to check you've covered all content",
      "Make flashcards for processes like mitosis, meiosis and protein synthesis",
    ],
    keyTopics: ["Cell Biology", "Multicellular Organisms", "Life on Earth", "DNA and Genes", "Inheritance", "Photosynthesis", "Respiration", "Evolution"],
    assessmentStructure: "Two question papers: Paper 1 (multiple choice, 25 marks) and Paper 2 (extended answers, 75 marks). No coursework, but an assignment worth 20% is added.",
    usefulResources: [
      { name: "SQA Past Papers – National 5 Biology", url: "https://www.sqa.org.uk/sqa/47371.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 Biology", url: "https://www.bbc.co.uk/bitesize/subjects/z4882hv", type: "Website" },
      { name: "Cognito – Biology Revision Videos", url: "https://www.cognitoedu.org", type: "Video" },
    ],
    relatedCareers: [],
  },
  {
    name: "Chemistry",
    level: "National 5",
    category: "STEM",
    description: "Explores chemical changes and the world of atoms, bonding, and reactions. Foundation for pharmacy, chemical engineering, and materials science.",
    examBoards: ["SQA"],
    studyTips: [
      "Learn the periodic table patterns — they underpin many questions",
      "Practise balancing equations and mole calculations",
      "Understand the difference between ionic, covalent and metallic bonding",
      "Use the data booklet in exams — practise finding values quickly",
      "Make a list of all the required practical techniques",
    ],
    keyTopics: ["Chemical Changes & Structure", "Nature's Chemistry", "Chemistry in Society", "Atomic Structure", "Bonding", "Acids & Bases", "Moles", "Organic Chemistry"],
    assessmentStructure: "Two question papers: Paper 1 (multiple choice, 25 marks) and Paper 2 (extended answers, 75 marks). Assignment worth 20%.",
    usefulResources: [
      { name: "SQA Past Papers – National 5 Chemistry", url: "https://www.sqa.org.uk/sqa/47374.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 Chemistry", url: "https://www.bbc.co.uk/bitesize/subjects/z4dqxnb", type: "Website" },
      { name: "Chemrevise – Chemistry Notes", url: "https://chemrevise.org", type: "Revision Guide" },
    ],
    relatedCareers: [],
  },
  {
    name: "Physics",
    level: "National 5",
    category: "STEM",
    description: "Covers electricity, forces, waves, radiation and space. Underpins engineering, physics, and technology degrees.",
    examBoards: ["SQA"],
    studyTips: [
      "Learn all the key equations and practise using the relationships sheet",
      "Draw diagrams for circuits, ray diagrams, and force problems",
      "Check units carefully in every calculation",
      "Watch Physics and Maths Tutor videos for hard concepts",
      "Use SQA Understanding Standards to see what full-mark answers look like",
    ],
    keyTopics: ["Electricity", "Properties of Matter", "Waves", "Radiation", "Dynamics", "Space", "Forces", "Nuclear Radiation"],
    assessmentStructure: "Two question papers: Paper 1 (multiple choice, 25 marks) and Paper 2 (extended answers, 75 marks). Assignment worth 20%.",
    usefulResources: [
      { name: "SQA Past Papers – National 5 Physics", url: "https://www.sqa.org.uk/sqa/47377.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 Physics", url: "https://www.bbc.co.uk/bitesize/subjects/zqp2pv4", type: "Website" },
      { name: "Physics & Maths Tutor – Revision", url: "https://www.physicsandmathstutor.com", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "History",
    level: "National 5",
    category: "Humanities",
    description: "Examines Scottish, British and European/World history. Develops critical thinking and source analysis skills valued by law, journalism and politics.",
    examBoards: ["SQA"],
    studyTips: [
      "Learn specific dates, names, and statistics for each topic",
      "Practise source-based questions — identify bias and purpose",
      "Use PEE (Point, Evidence, Explain) for essay paragraphs",
      "Make timelines for key periods to understand cause and effect",
      "Read historiographical debate to strengthen essays",
    ],
    keyTopics: ["Scottish History", "British History", "European & World History", "Source Evaluation", "Historical Essay Writing"],
    assessmentStructure: "Two question papers: Paper 1 (Scottish contexts, 36 marks) and Paper 2 (British, European/World contexts, 44 marks). Assignment worth 27%.",
    usefulResources: [
      { name: "SQA Past Papers – National 5 History", url: "https://www.sqa.org.uk/sqa/47378.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 History", url: "https://www.bbc.co.uk/bitesize/subjects/zj26n39", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "Geography",
    level: "National 5",
    category: "Humanities",
    description: "Studies human and physical geography including climate, population, and global issues. Valuable for environmental science and urban planning careers.",
    examBoards: ["SQA"],
    studyTips: [
      "Learn to describe and explain patterns on maps and graphs",
      "Practise drawing accurate, labelled diagrams",
      "Know the specific case studies inside out",
      "Link human and physical geography topics where possible",
      "Use recent news articles for global issues questions",
    ],
    keyTopics: ["Physical Environments", "Human Environments", "Global Issues", "Map Skills", "Climate Change", "Development & Health"],
    assessmentStructure: "Two question papers: Paper 1 (Physical & Human environments, 44 marks) and Paper 2 (Global Issues & Application of Geographical Skills, 36 marks). Assignment worth 20%.",
    usefulResources: [
      { name: "SQA Past Papers – National 5 Geography", url: "https://www.sqa.org.uk/sqa/47376.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 Geography", url: "https://www.bbc.co.uk/bitesize/subjects/zcwy2hv", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "Modern Studies",
    level: "National 5",
    category: "Humanities",
    description: "Covers Scottish and UK politics, social issues, and international relations. Excellent preparation for law, politics, social work, and journalism.",
    examBoards: ["SQA"],
    studyTips: [
      "Stay up to date with current affairs — use BBC News Scotland",
      "Learn key political concepts (democracy, representation, devolution)",
      "Practise evaluating sources for reliability and bias",
      "Use specific case studies with facts and statistics",
      "Link theoretical knowledge to real-world examples",
    ],
    keyTopics: ["Democracy in Scotland & the UK", "Social Issues in the UK", "International Issues", "Source Evaluation", "Rights & Responsibilities"],
    assessmentStructure: "Two question papers: Paper 1 (60 marks) and Paper 2 (source-based, 30 marks). Assignment worth 30%.",
    usefulResources: [
      { name: "SQA Past Papers – National 5 Modern Studies", url: "https://www.sqa.org.uk/sqa/47381.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 Modern Studies", url: "https://www.bbc.co.uk/bitesize/subjects/ztvfr82", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "Computing Science",
    level: "National 5",
    category: "Technology",
    description: "Teaches programming, data representation, computer systems and software development. Pathway to computing, software engineering and data science degrees.",
    examBoards: ["SQA"],
    studyTips: [
      "Practise coding in Python — it's the most common language used",
      "Learn the standard algorithms (linear search, bubble sort, etc.)",
      "Understand binary, hexadecimal and data types thoroughly",
      "Draw structure diagrams and flowcharts to plan programs",
      "Debug your own code and understand each line",
    ],
    keyTopics: ["Software Design & Development", "Computer Systems", "Database Design & Development", "Web Design & Development", "Algorithms", "Programming"],
    assessmentStructure: "One question paper (110 marks) plus a practical assignment (coursework, 60 marks).",
    usefulResources: [
      { name: "SQA Past Papers – National 5 Computing", url: "https://www.sqa.org.uk/sqa/47375.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 Computing Science", url: "https://www.bbc.co.uk/bitesize/subjects/z7hs34j", type: "Website" },
      { name: "W3Schools – Web & Programming", url: "https://www.w3schools.com", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "French",
    level: "National 5",
    category: "Languages",
    description: "Develops reading, writing, listening and talking in French across real-world contexts. Opens doors to international business, translation, and European study.",
    examBoards: ["SQA"],
    studyTips: [
      "Practise listening to French podcasts and radio daily",
      "Learn a bank of opinion phrases, connectives and justification vocabulary",
      "Practise writing directed writing using a bullet-point structure",
      "Record yourself speaking and listen back to improve pronunciation",
      "Use Duolingo for daily vocabulary practice",
    ],
    keyTopics: ["Society", "Learning", "Employability", "Culture", "Reading for Understanding", "Listening", "Writing", "Talking"],
    assessmentStructure: "Four components: Reading (30 marks), Writing (20 marks), Listening (20 marks), and Talking (30 marks).",
    usefulResources: [
      { name: "SQA Past Papers – National 5 French", url: "https://www.sqa.org.uk/sqa/47380.html", type: "Past Papers" },
      { name: "BBC Bitesize – National 5 French", url: "https://www.bbc.co.uk/bitesize/subjects/zgdqxnb", type: "Website" },
      { name: "Duolingo – French Practice", url: "https://www.duolingo.com", type: "Website" },
    ],
    relatedCareers: [],
  },

  // ── Scottish Higher subjects ───────────────────────────────────────────────
  {
    name: "Mathematics",
    level: "Higher",
    category: "STEM",
    description: "Scottish Higher Mathematics covers advanced algebra, calculus, trigonometry, and vectors. Essential for engineering, physics, economics, and computing degrees at Scottish universities.",
    examBoards: ["SQA"],
    studyTips: [
      "Higher Maths is a big step up — start past papers from October",
      "Learn the exact wording of rules (differentiation, integration, wave function)",
      "Check every answer against the marking scheme to understand partial credit",
      "Use Maths 777 and Squarepanda for SQA-specific practice",
      "Group study works well — explain concepts to others to test yourself",
    ],
    keyTopics: ["Expressions & Functions", "Relationships & Calculus", "Applications", "Differentiation", "Integration", "Polynomials", "Circles", "Vectors", "Logarithms"],
    assessmentStructure: "Two question papers: Paper 1 (non-calculator, 70 marks) and Paper 2 (calculator, 80 marks).",
    usefulResources: [
      { name: "SQA Past Papers – Higher Maths", url: "https://www.sqa.org.uk/sqa/47408.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher Maths", url: "https://www.bbc.co.uk/bitesize/subjects/zhdgr82", type: "Website" },
      { name: "Maths 777 – Higher Maths", url: "https://www.maths777.com", type: "Practice Questions" },
      { name: "Squarepanda – SQA Revision", url: "https://www.squarepanda.co.uk", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "English",
    level: "Higher",
    category: "Humanities",
    description: "Scottish Higher English demands sophisticated textual analysis, persuasive writing, and critical engagement with literature. Required by most Scottish university courses.",
    examBoards: ["SQA"],
    studyTips: [
      "Read the Scottish Set Texts thoroughly — know key quotes for all three genres",
      "Practise Critical Essays under timed conditions",
      "Learn to write analytically about technique, not just content",
      "Use the SQA marking instructions to see exactly what full marks require",
      "Write a discursive essay draft every fortnight and get teacher feedback",
    ],
    keyTopics: ["Reading for Understanding, Analysis and Evaluation", "Critical Essay", "Scottish Texts", "Portfolio Writing", "Persuasive Writing", "Literature Analysis"],
    assessmentStructure: "Two exam papers: Reading for UAA (1 hour 30 min) and Critical Essay (1 hour 30 min). Portfolio (25% of overall mark).",
    usefulResources: [
      { name: "SQA Past Papers – Higher English", url: "https://www.sqa.org.uk/sqa/47404.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher English", url: "https://www.bbc.co.uk/bitesize/subjects/zr9d7ty", type: "Website" },
      { name: "LitCharts – Text Analysis", url: "https://www.litcharts.com", type: "Revision Guide" },
    ],
    relatedCareers: [],
  },
  {
    name: "Biology",
    level: "Higher",
    category: "STEM",
    description: "Scottish Higher Biology explores cell biology, physiology, genetics and evolution at university-entry level. Gateway to medicine, dentistry, nursing and life sciences.",
    examBoards: ["SQA"],
    studyTips: [
      "Learn all the named examples precisely — generic answers rarely gain full marks",
      "Make detailed notes on each unit area and test yourself with past questions",
      "Understand experimental design for the assignment",
      "Use diagrams of processes (replication, transcription, translation) to revise",
      "Higher Biology has a lot of content — start revision early",
    ],
    keyTopics: ["Cell Biology", "Physiology & Health", "Sustainability & Interdependence", "DNA & Gene Expression", "Genetics", "Photosynthesis & Respiration", "Evolution"],
    assessmentStructure: "Two papers: Paper 1 (multiple choice, 25 marks) and Paper 2 (extended answers, 95 marks). Assignment worth 20%.",
    usefulResources: [
      { name: "SQA Past Papers – Higher Biology", url: "https://www.sqa.org.uk/sqa/47402.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher Biology", url: "https://www.bbc.co.uk/bitesize/subjects/z4kgr82", type: "Website" },
      { name: "Cognito – Biology Revision", url: "https://www.cognitoedu.org", type: "Video" },
    ],
    relatedCareers: [],
  },
  {
    name: "Chemistry",
    level: "Higher",
    category: "STEM",
    description: "Scottish Higher Chemistry covers organic chemistry, physical chemistry, and inorganic topics at depth. Essential for pharmacy, chemical engineering, and biochemistry.",
    examBoards: ["SQA"],
    studyTips: [
      "Learn the full systematic naming of organic compounds",
      "Mole calculations appear in every exam — master them early",
      "Use the SQA data booklet in every practice question",
      "Understand spectroscopy and chromatography techniques",
      "Write detailed revision notes using the SQA course specification",
    ],
    keyTopics: ["Chemical Changes & Structure", "Nature's Chemistry", "Chemistry in Society", "Organic Chemistry", "Stoichiometry", "Spectroscopy", "Thermodynamics", "Electrochemistry"],
    assessmentStructure: "Two papers: Paper 1 (multiple choice, 25 marks) and Paper 2 (extended answers, 95 marks). Assignment worth 20%.",
    usefulResources: [
      { name: "SQA Past Papers – Higher Chemistry", url: "https://www.sqa.org.uk/sqa/47403.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher Chemistry", url: "https://www.bbc.co.uk/bitesize/subjects/zrxxpv4", type: "Website" },
      { name: "Chemrevise – Chemistry Notes", url: "https://chemrevise.org", type: "Revision Guide" },
    ],
    relatedCareers: [],
  },
  {
    name: "Physics",
    level: "Higher",
    category: "STEM",
    description: "Scottish Higher Physics covers our physical world from quantum mechanics to cosmology. Prerequisite for engineering, physics and astrophysics at Scottish universities.",
    examBoards: ["SQA"],
    studyTips: [
      "Know every equation and when each applies — don't just memorise",
      "Practise deriving answers from first principles for tricky questions",
      "Use the relationships sheet intelligently in the exam",
      "Watch Physics and Maths Tutor videos for conceptual understanding",
      "Higher Physics involves a lot of graph interpretation — practise this skill",
    ],
    keyTopics: ["Our Dynamic Universe", "Particles and Waves", "Electricity", "Uncertainties", "Kinematics", "Forces", "Quantum Theory", "Nuclear Physics", "Electromagnetism"],
    assessmentStructure: "Two papers: Paper 1 (multiple choice, 25 marks) and Paper 2 (extended answers, 95 marks). Assignment worth 20%.",
    usefulResources: [
      { name: "SQA Past Papers – Higher Physics", url: "https://www.sqa.org.uk/sqa/47411.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher Physics", url: "https://www.bbc.co.uk/bitesize/subjects/zcgr82", type: "Website" },
      { name: "Physics & Maths Tutor – Higher", url: "https://www.physicsandmathstutor.com", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "Modern Studies",
    level: "Higher",
    category: "Humanities",
    description: "Higher Modern Studies examines Scottish and UK politics, international relations and social justice in depth. Strong preparation for law, politics, economics and social work degrees.",
    examBoards: ["SQA"],
    studyTips: [
      "Follow Scottish political news closely — BBC Scotland and The Herald",
      "Use specific statistical evidence in every argument",
      "Learn to write a balanced extended response with a clear conclusion",
      "Practise evaluating sources for selectivity and objectivity",
      "Know the political systems of your chosen international comparison country",
    ],
    keyTopics: ["Democracy in Scotland & the UK", "Social Issues in the UK", "International Issues", "Electoral Systems", "Source Evaluation", "Human Rights"],
    assessmentStructure: "Two question papers: Paper 1 (90 marks) and Paper 2 (source evaluation, 30 marks). Assignment worth 30%.",
    usefulResources: [
      { name: "SQA Past Papers – Higher Modern Studies", url: "https://www.sqa.org.uk/sqa/47410.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher Modern Studies", url: "https://www.bbc.co.uk/bitesize/subjects/zvpfr82", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "History",
    level: "Higher",
    category: "Humanities",
    description: "Scottish Higher History demands sophisticated source evaluation and essay writing about Scottish, British and world events. Excellent for humanities university courses.",
    examBoards: ["SQA"],
    studyTips: [
      "Memorise key dates, turning points, and historians' arguments",
      "Write essay plans before attempting full answers under time pressure",
      "Use historiographical perspectives to distinguish excellent from good answers",
      "Practise source evaluation — bias, purpose, reliability, and corroboration",
      "Make a revision grid linking causes, events, and consequences",
    ],
    keyTopics: ["Scottish History", "British History", "European & World History", "Historiography", "Source Evaluation", "Historical Essay Writing"],
    assessmentStructure: "Two papers: Paper 1 (Scottish contexts, 36 marks) and Paper 2 (British and European/World, 44 marks). Assignment worth 27%.",
    usefulResources: [
      { name: "SQA Past Papers – Higher History", url: "https://www.sqa.org.uk/sqa/47407.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher History", url: "https://www.bbc.co.uk/bitesize/subjects/zmpkwxs", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "Psychology",
    level: "Higher",
    category: "Social Sciences",
    description: "Examines human behaviour through biological, cognitive, and social psychology. Popular with students aiming for psychology, medicine, social work and education degrees.",
    examBoards: ["SQA"],
    studyTips: [
      "Learn key studies with researcher names, findings and methodology",
      "Understand ethical issues in psychology research thoroughly",
      "Practise applying theories to novel scenarios",
      "Create study cards for each major theory and evaluation point",
      "Higher Psychology rewards critical thinking — practise AO2 skills",
    ],
    keyTopics: ["Sleep & Dreams", "Memory", "Social Behaviour", "Research Methods", "Individual Behaviour", "Biological Psychology", "Cognitive Psychology", "Social Psychology"],
    assessmentStructure: "One question paper (120 marks). Assignment worth 33% of overall mark.",
    usefulResources: [
      { name: "SQA Past Papers – Higher Psychology", url: "https://www.sqa.org.uk/sqa/47412.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher Psychology", url: "https://www.bbc.co.uk/bitesize/subjects/zmgr82", type: "Website" },
      { name: "Simply Psychology – Core Studies", url: "https://www.simplypsychology.org", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "Business Management",
    level: "Higher",
    category: "Business",
    description: "Covers business in a global context, management of people, finance, and marketing. Foundation for business, management, accounting and economics degrees.",
    examBoards: ["SQA"],
    studyTips: [
      "Learn the key theories (Maslow, McGregor, Herzberg) with evaluation points",
      "Practise extended response questions using SOAT structure",
      "Read business news — The Scotsman, BBC Business — for real examples",
      "Create flashcards for all the key business terminology",
      "Link theories to real Scottish and UK businesses in your answers",
    ],
    keyTopics: ["Business in Contemporary Society", "Management of People", "Management of Finance", "Operations Management", "Marketing", "Decision Making"],
    assessmentStructure: "Two question papers: Paper 1 (60 marks) and Paper 2 (extended responses, 60 marks). Assignment worth 30%.",
    usefulResources: [
      { name: "SQA Past Papers – Higher Business Management", url: "https://www.sqa.org.uk/sqa/47403.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher Business Management", url: "https://www.bbc.co.uk/bitesize/subjects/zj7f4qt", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "Economics",
    level: "Higher",
    category: "Social Sciences",
    description: "Introduces microeconomics and macroeconomics including markets, government policy, and international trade. Valuable for economics, finance, and public policy degrees.",
    examBoards: ["SQA"],
    studyTips: [
      "Draw economic diagrams accurately (supply/demand, AD/AS, PPC)",
      "Learn to use data from stimulus material in your answers",
      "Understand the difference between micro and macroeconomic concepts",
      "Practise extended responses linking theory to real UK economic data",
      "Follow ONS and Bank of England data releases for current context",
    ],
    keyTopics: ["Economic Concepts", "Microeconomics", "Macroeconomics", "International Economics", "Market Failure", "Government Policy", "Demand & Supply"],
    assessmentStructure: "Two question papers: Paper 1 (50 marks) and Paper 2 (50 marks). Assignment worth 30%.",
    usefulResources: [
      { name: "SQA Past Papers – Higher Economics", url: "https://www.sqa.org.uk/sqa/47405.html", type: "Past Papers" },
      { name: "BBC Bitesize – Higher Economics", url: "https://www.bbc.co.uk/bitesize/subjects/zt2f4qt", type: "Website" },
      { name: "Economics Help – Revision", url: "https://www.economicshelp.org", type: "Website" },
    ],
    relatedCareers: [],
  },

  // ── Advanced Higher subjects ───────────────────────────────────────────────
  {
    name: "Mathematics",
    level: "Advanced Higher",
    category: "STEM",
    description: "Advanced Higher Mathematics is broadly equivalent to first-year university mathematics. Covers calculus, matrices, complex numbers, and proof. Highly valued by Scottish and UK universities.",
    examBoards: ["SQA"],
    studyTips: [
      "Advanced Higher is a significant leap — treat it like university study",
      "Work through every past paper and compare to published solutions",
      "Learn formal proof techniques thoroughly",
      "Get comfortable with matrices, determinants and transformations",
      "Complex numbers and differential equations require sustained practice",
    ],
    keyTopics: ["Methods in Algebra & Calculus", "Applications of Algebra & Calculus", "Geometry, Proof and Systems of Equations", "Complex Numbers", "Matrices", "Proof", "Differential Equations"],
    assessmentStructure: "Two question papers: Paper 1 (non-calculator, 35 marks) and Paper 2 (calculator, 75 marks). No coursework.",
    usefulResources: [
      { name: "SQA Past Papers – Advanced Higher Maths", url: "https://www.sqa.org.uk/sqa/74763.html", type: "Past Papers" },
      { name: "Maths 777 – Advanced Higher", url: "https://www.maths777.com", type: "Practice Questions" },
      { name: "Physics & Maths Tutor – AH Maths", url: "https://www.physicsandmathstutor.com", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "Chemistry",
    level: "Advanced Higher",
    category: "STEM",
    description: "Advanced Higher Chemistry covers physical chemistry, organic synthesis, and analytical techniques at near-university depth. Essential for chemistry and biochemistry degree applicants.",
    examBoards: ["SQA"],
    studyTips: [
      "Understand reaction mechanisms — don't just memorise the outcomes",
      "Advanced NMR and spectroscopy interpretation requires focused practice",
      "The project/research component is a major differentiator — start early",
      "Revisit your Higher knowledge and extend it rather than starting fresh",
      "Practise quantitative problem solving with multi-step calculations",
    ],
    keyTopics: ["Electronic Structure & The Periodic Table", "Molecular Orbitals", "Reaction Feasibility", "Organic Chemistry", "Spectroscopy", "Analytical Chemistry", "Research Skills"],
    assessmentStructure: "Two question papers: Paper 1 (30 marks) and Paper 2 (90 marks). Research project worth 30% of overall mark.",
    usefulResources: [
      { name: "SQA Past Papers – Advanced Higher Chemistry", url: "https://www.sqa.org.uk/sqa/74764.html", type: "Past Papers" },
      { name: "Chemrevise – Advanced Chemistry", url: "https://chemrevise.org", type: "Revision Guide" },
    ],
    relatedCareers: [],
  },
  {
    name: "Physics",
    level: "Advanced Higher",
    category: "STEM",
    description: "Advanced Higher Physics explores mechanics, electromagnetism, quantum theory and wave phenomena at university-entrance level. Strong preparation for physics and engineering degrees.",
    examBoards: ["SQA"],
    studyTips: [
      "Advanced Higher Physics involves significant mathematical derivation — be comfortable with calculus",
      "Understand the experimental project requirements early in the year",
      "The rotational dynamics unit is often found hardest — start it early",
      "Practise applying concepts to unfamiliar scenarios in past papers",
      "Consolidate Higher Physics fully before progressing to Advanced Higher content",
    ],
    keyTopics: ["Rotational Motion", "Gravitation", "Electromagnetism", "Wave Phenomena", "Quantum Theory", "Special Relativity", "Experimental Physics"],
    assessmentStructure: "Two question papers: Paper 1 (30 marks) and Paper 2 (90 marks). Experimental project worth 30%.",
    usefulResources: [
      { name: "SQA Past Papers – Advanced Higher Physics", url: "https://www.sqa.org.uk/sqa/74765.html", type: "Past Papers" },
      { name: "Physics & Maths Tutor – Advanced Higher", url: "https://www.physicsandmathstutor.com", type: "Website" },
    ],
    relatedCareers: [],
  },
  {
    name: "English",
    level: "Advanced Higher",
    category: "Humanities",
    description: "Advanced Higher English develops independent literary research and sustained analytical writing. Excellent preparation for English, law, journalism and humanities degrees.",
    examBoards: ["SQA"],
    studyTips: [
      "The Specialist Study is the centrepiece — choose your text carefully and early",
      "Read secondary criticism to support your analysis",
      "Practise writing 2000-word analytical essays with a clear argument",
      "Advanced Higher demands original critical perspective, not just description",
      "Engage with Scottish literary tradition as well as wider Anglophone literature",
    ],
    keyTopics: ["Textual Analysis", "Critical Essay", "Specialist Study", "Dissertation", "Scottish Literature", "Literary Theory"],
    assessmentStructure: "Two exam papers: Textual Analysis (1 hr 30 min) and Critical Essay (1 hr 30 min). Specialist Study (dissertation) worth 40%.",
    usefulResources: [
      { name: "SQA Past Papers – Advanced Higher English", url: "https://www.sqa.org.uk/sqa/74762.html", type: "Past Papers" },
      { name: "LitCharts – Text Analysis", url: "https://www.litcharts.com", type: "Revision Guide" },
    ],
    relatedCareers: [],
  },
  {
    name: "Biology",
    level: "Advanced Higher",
    category: "STEM",
    description: "Advanced Higher Biology covers molecular biology, animal behaviour, and investigative research skills. Strongly valued by medicine, dentistry, and life science universities.",
    examBoards: ["SQA"],
    studyTips: [
      "Master the molecular biology unit — it underpins nearly all other topics",
      "The research investigation is a significant component — choose a feasible topic",
      "Practise statistical analysis techniques (chi-squared, t-test, correlation)",
      "Link Advanced Higher content to what you know from Higher and National 5",
      "Write up experiments clearly with full methodology and conclusions",
    ],
    keyTopics: ["Molecular Biology", "Animal Behaviour", "Forensic Biology", "Research Investigation", "Statistical Analysis", "Genetics", "Evolution"],
    assessmentStructure: "Two papers: Paper 1 (30 marks) and Paper 2 (90 marks). Research investigation worth 30%.",
    usefulResources: [
      { name: "SQA Past Papers – Advanced Higher Biology", url: "https://www.sqa.org.uk/sqa/74761.html", type: "Past Papers" },
      { name: "BBC Bitesize – Advanced Higher Biology", url: "https://www.bbc.co.uk/bitesize/subjects/zkg8d2p", type: "Website" },
    ],
    relatedCareers: [],
  },
];

async function main() {
  console.log(`Seeding ${scottishSubjects.length} Scottish subjects...`);

  for (const subject of scottishSubjects) {
    await db.insert(subjectsTable).values(subject).onConflictDoNothing();
    console.log(`  ✓ ${subject.level} ${subject.name}`);
  }

  console.log("Done!");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
