import { db, institutionsTable } from "@workspace/db";

const newProviders = [
  // ── NORTH WEST ────────────────────────────────────────────────────────────────
  {
    name: "BBC Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "North West",
    city: "Salford",
    description: "Join the BBC through apprenticeship programmes in journalism, technology, business and production at MediaCityUK in Salford. Earn a competitive salary from £22,000 with no tuition fees and placements across the UK.",
    websiteUrl: "https://www.bbc.co.uk/careers/trainee-schemes-and-apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade 4+. Degree and Higher Apprenticeships available requiring A-levels or equivalent.",
    ucasPoints: null,
    studentSatisfaction: 4.3,
    notableSubjects: ["Journalism", "Software Engineering", "Business Administration", "Data Science", "Project Management"],
    facilities: ["MediaCityUK campus", "Broadcasting studios", "Digital production suites", "News operations centres"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-14", "2026-09-10"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "September 2026",
  },
  {
    name: "Co-op Group Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "North West",
    city: "Manchester",
    description: "The Co-op offers apprenticeships in retail management, digital, HR, finance and funeral care from its Manchester base, with opportunities across England, Scotland and Wales. Salaries from £21,000.",
    websiteUrl: "https://careers.co-op.co.uk/earlytalent/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade 4+. No prior experience required.",
    ucasPoints: null,
    studentSatisfaction: 4.1,
    notableSubjects: ["Retail Management", "Digital Marketing", "HR", "Finance", "Supply Chain"],
    facilities: ["Head office Manchester", "3,800 food stores", "Distribution centres"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-05", "2026-10-08"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },
  {
    name: "AstraZeneca Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "North West",
    city: "Macclesfield",
    description: "AstraZeneca offers science and technical apprenticeships at its Macclesfield site in pharmaceutical sciences, engineering, and IT. Earn from £20,000 with a world-class R&D environment and excellent career prospects.",
    websiteUrl: "https://careers.astrazeneca.com/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths and Science grade 5+. A-levels in Science subjects preferred for Higher Apprenticeships.",
    ucasPoints: null,
    studentSatisfaction: 4.4,
    notableSubjects: ["Pharmaceutical Science", "Chemical Engineering", "Laboratory Science", "IT Support", "Project Management"],
    facilities: ["State-of-the-art labs", "Manufacturing facilities", "Research centres"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-21", "2026-09-17"],
    applicationDeadline: "January 2027",
    applicationsOpen: "September 2026",
  },

  // ── YORKSHIRE ────────────────────────────────────────────────────────────────
  {
    name: "ASDA Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Yorkshire",
    city: "Leeds",
    description: "ASDA provides retail and management apprenticeships across its stores, distribution centres and Leeds head office, covering retail leadership, supply chain, and business operations. Salaries from £20,000.",
    websiteUrl: "https://www.asda.jobs/early-careers/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade 4+. Passion for retail.",
    ucasPoints: null,
    studentSatisfaction: 4.0,
    notableSubjects: ["Retail Management", "Supply Chain", "Business Administration", "Digital Marketing", "HR"],
    facilities: ["Leeds head office", "600+ stores", "Distribution centres"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-11", "2026-09-24"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },
  {
    name: "Siemens UK Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Yorkshire",
    city: "Goole",
    description: "Siemens Mobility offers engineering apprenticeships at its train manufacturing facility in Goole, Yorkshire — building rolling stock for the UK's rail network. Earn from £22,000 with world-class engineering training.",
    websiteUrl: "https://www.siemens.co.uk/en/company/jobs/apprenticeships.html",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths and English grade 4+. GCSE Science or Technology grade 4+ preferred.",
    ucasPoints: null,
    studentSatisfaction: 4.5,
    notableSubjects: ["Mechanical Engineering", "Electrical Engineering", "Manufacturing", "Maintenance Engineering", "Mechatronics"],
    facilities: ["Goole manufacturing plant", "Training workshops", "Modern production lines", "Engineering labs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-28", "2026-10-15"],
    applicationDeadline: "March 2027",
    applicationsOpen: "September 2026",
  },

  // ── MIDLANDS ──────────────────────────────────────────────────────────────────
  {
    name: "Jaguar Land Rover Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Midlands",
    city: "Coventry",
    description: "JLR's award-winning apprenticeship programme offers roles in engineering, manufacturing and business across Coventry, Solihull and beyond. Salaries from £18,500 rising to £30,000+ on qualification.",
    websiteUrl: "https://www.jaguarlandrovercareers.com/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths and English grade 4+. GCSE Science or DT grade 4+ for engineering routes.",
    ucasPoints: null,
    studentSatisfaction: 4.6,
    notableSubjects: ["Mechanical Engineering", "Electrical Engineering", "Manufacturing", "Software Engineering", "Business Management"],
    facilities: ["Coventry HQ", "Solihull plant", "National Automotive Innovation Centre"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-04", "2026-09-03"],
    applicationDeadline: "February 2027",
    applicationsOpen: "September 2026",
  },
  {
    name: "KPMG School Leaver Programme (Birmingham)",
    type: "Apprenticeship Provider" as const,
    region: "Midlands",
    city: "Birmingham",
    description: "KPMG's Birmingham School Leaver Programme offers a professional qualification (ACA) while earning a salary from £25,000, with experience across audit, tax, consulting and technology. ACA exam fees fully funded.",
    websiteUrl: "https://www.kpmgcareers.co.uk/school-leavers",
    russellGroup: false,
    ranking: null,
    entryRequirements: "96 UCAS points (BBB at A-level). GCSE Maths and English grade 5+.",
    ucasPoints: 96,
    studentSatisfaction: 4.5,
    notableSubjects: ["Accounting", "Audit", "Tax", "Technology Consulting", "Business Advisory"],
    facilities: ["Birmingham city centre office", "Training facilities", "Mentoring programmes"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-18", "2026-11-05"],
    applicationDeadline: "January 2027",
    applicationsOpen: "September 2026",
  },
  {
    name: "Amazon UK Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Midlands",
    city: "Coalville",
    description: "Amazon offers apprenticeships in operations, IT, data science and engineering across its UK fulfilment centres and tech hubs. Earn from £25,000 with strong career progression and Amazon employee benefits.",
    websiteUrl: "https://www.amazon.jobs/en/landing_pages/apprenticeships-uk",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade 4+. Interest in IT and computing for tech roles.",
    ucasPoints: null,
    studentSatisfaction: 4.2,
    notableSubjects: ["Operations Management", "Software Engineering", "Data Science", "IT Support", "Supply Chain Management"],
    facilities: ["Fulfilment centres across UK", "Tech offices", "Training academies"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-07", "2026-09-10"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },

  // ── NORTH EAST ────────────────────────────────────────────────────────────────
  {
    name: "Nissan Motor Manufacturing UK Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "North East",
    city: "Sunderland",
    description: "Nissan's Sunderland plant is one of Europe's most productive car factories. Their apprenticeship scheme provides outstanding training in manufacturing, engineering and EV production. Competitive salary from £20,000.",
    websiteUrl: "https://www.nissan-global.com/EN/CAREERS/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths and English grade 4+. GCSE Science or Engineering grade 4+ preferred.",
    ucasPoints: null,
    studentSatisfaction: 4.4,
    notableSubjects: ["Manufacturing Engineering", "Mechanical Engineering", "Electrical Engineering", "Robotics"],
    facilities: ["Sunderland manufacturing plant", "Training centre", "EV production lines"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-20", "2026-10-22"],
    applicationDeadline: "March 2027",
    applicationsOpen: "September 2026",
  },
  {
    name: "Sage Group Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "North East",
    city: "Newcastle upon Tyne",
    description: "Sage, a global leader in business technology, offers tech apprenticeships at its Newcastle HQ in software development, data science, cybersecurity and business analysis. Earn from £22,000 with excellent benefits.",
    websiteUrl: "https://www.sage.com/en-gb/company/careers/early-careers/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths and English grade 4+. Interest in technology and business.",
    ucasPoints: null,
    studentSatisfaction: 4.3,
    notableSubjects: ["Software Development", "Data Science", "Cybersecurity", "Business Analysis", "Cloud Computing"],
    facilities: ["Newcastle HQ", "Innovation labs", "Tech training suites"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-14", "2026-09-17"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },

  // ── SCOTLAND ──────────────────────────────────────────────────────────────────
  {
    name: "Baillie Gifford Investment Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Scotland",
    city: "Edinburgh",
    description: "Baillie Gifford, one of the UK's largest investment managers, offers school leaver programmes in investment management, technology and business operations from Edinburgh. Salaries from £22,000 with qualifications funded.",
    websiteUrl: "https://www.bailliegifford.com/en/uk/about-us/careers/early-talent/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Highers ABB or A-levels BBC. GCSE/National 5 Maths and English grade C+.",
    ucasPoints: 112,
    studentSatisfaction: 4.6,
    notableSubjects: ["Investment Management", "Finance", "Data Analysis", "Technology", "Business Operations"],
    facilities: ["Edinburgh HQ", "Investment research library", "Modern offices"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-04", "2026-10-08"],
    applicationDeadline: "January 2027",
    applicationsOpen: "September 2026",
  },
  {
    name: "Scottish Power Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Scotland",
    city: "Glasgow",
    description: "ScottishPower's apprenticeship programme focuses on engineering for the energy transition, offering roles in wind energy, smart grids and electrical engineering from Glasgow. Competitive salary from £19,000.",
    websiteUrl: "https://careers.scottishpower.com/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "National 5 or GCSE Maths and English grade C+. Science or Engineering subjects beneficial.",
    ucasPoints: null,
    studentSatisfaction: 4.2,
    notableSubjects: ["Electrical Engineering", "Renewable Energy", "Smart Grid Technology", "Mechanical Engineering"],
    facilities: ["Glasgow HQ", "Wind farms", "Training centres", "Innovation hubs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-28", "2026-10-15"],
    applicationDeadline: "February 2027",
    applicationsOpen: "September 2026",
  },

  // ── WALES ─────────────────────────────────────────────────────────────────────
  {
    name: "Welsh Government Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Wales",
    city: "Cardiff",
    description: "The Welsh Government offers apprenticeships across public sector departments in Cardiff, covering business administration, digital, HR, law and policy. Welsh language skills valued. Salaries typically £21,000–£26,000.",
    websiteUrl: "https://gov.wales/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Welsh/English and Maths grade C+. Welsh language skills desirable for some roles.",
    ucasPoints: null,
    studentSatisfaction: 4.0,
    notableSubjects: ["Business Administration", "Digital Services", "Human Resources", "Policy Analysis", "Legal Services"],
    facilities: ["Cardiff Bay offices", "Modern government buildings", "Training facilities"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-11", "2026-10-01"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },
  {
    name: "Admiral Group Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Wales",
    city: "Cardiff",
    description: "Admiral Insurance, Wales's largest private employer, runs apprenticeship programmes in business, finance, technology and customer operations from Cardiff. Earn from £21,000 with a profit share scheme.",
    websiteUrl: "https://admiralcareers.co.uk/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade 4+. Enthusiasm for business and customer service.",
    ucasPoints: null,
    studentSatisfaction: 4.3,
    notableSubjects: ["Insurance", "Business Administration", "Data Analysis", "Software Development", "Customer Operations"],
    facilities: ["Cardiff HQ", "Newport office", "Training rooms"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-25", "2026-09-10"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },

  // ── EAST OF ENGLAND ───────────────────────────────────────────────────────────
  {
    name: "ARM Holdings Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "East of England",
    city: "Cambridge",
    description: "ARM, whose processor designs power the majority of the world's mobile devices, offers degree and higher apprenticeships in chip design, software engineering and systems engineering from Cambridge. Salaries from £30,000.",
    websiteUrl: "https://careers.arm.com/early-careers",
    russellGroup: false,
    ranking: null,
    entryRequirements: "A-levels in Maths and Physics or Computer Science grade BBC+. GCSE Maths grade 6+.",
    ucasPoints: 112,
    studentSatisfaction: 4.7,
    notableSubjects: ["Chip Design", "Embedded Systems", "Software Engineering", "Computer Architecture", "Machine Learning"],
    facilities: ["Cambridge HQ", "World-class design labs", "Innovation centres"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-07-02", "2026-10-22"],
    applicationDeadline: "January 2027",
    applicationsOpen: "September 2026",
  },
  {
    name: "Barclays Apprenticeship Programme",
    type: "Apprenticeship Provider" as const,
    region: "East of England",
    city: "Northampton",
    description: "Barclays offers apprenticeships in banking, technology and data from its UK operations centre in Northampton and London, providing qualifications up to degree-level while earning from £24,000. Banking qualifications fully funded.",
    websiteUrl: "https://home.barclays/careers/early-talent/apprenticeships/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade 4+. A-levels in Maths or Computer Science beneficial for tech routes.",
    ucasPoints: null,
    studentSatisfaction: 4.2,
    notableSubjects: ["Banking", "Finance", "Software Engineering", "Data Science", "Cybersecurity"],
    facilities: ["Northampton operations hub", "Training academy", "Digital labs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-04", "2026-09-24"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },

  // ── SOUTH WEST ────────────────────────────────────────────────────────────────
  {
    name: "Airbus UK Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "South West",
    city: "Bristol",
    description: "Airbus in Filton, Bristol is a world centre for aircraft wing design. Their apprenticeships cover aerospace engineering, manufacturing, business and digital. Earn from £23,000 rising to £40,000+ for degree apprentices.",
    websiteUrl: "https://www.airbus.com/en/careers/students-and-graduates/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths and English grade 5+. A-levels in Maths and Physics preferred for engineering routes.",
    ucasPoints: 104,
    studentSatisfaction: 4.7,
    notableSubjects: ["Aerospace Engineering", "Mechanical Engineering", "Wing Design", "Manufacturing", "Digital Engineering"],
    facilities: ["Filton Aerospace Park", "Wing manufacturing facility", "Design labs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-11", "2026-10-01"],
    applicationDeadline: "February 2027",
    applicationsOpen: "September 2026",
  },
  {
    name: "EDF Energy Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "South West",
    city: "Gloucester",
    description: "EDF Energy operates the majority of the UK's nuclear power stations and offers engineering apprenticeships at its plants in Gloucestershire. Earn from £22,000 rising to £35,000+ on completion.",
    websiteUrl: "https://careers.edfenergy.com/early-careers/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths, English and Science grade 4+. A-levels in STEM subjects preferred for Higher Apprenticeships.",
    ucasPoints: null,
    studentSatisfaction: 4.4,
    notableSubjects: ["Nuclear Engineering", "Electrical Engineering", "Mechanical Engineering", "Control Systems"],
    facilities: ["Nuclear power stations", "Training centres", "Simulation suites"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-18", "2026-10-08"],
    applicationDeadline: "March 2027",
    applicationsOpen: "September 2026",
  },

  // ── LONDON (additional) ───────────────────────────────────────────────────────
  {
    name: "Goldman Sachs School Leaver Programme",
    type: "Apprenticeship Provider" as const,
    region: "London",
    city: "London",
    description: "Goldman Sachs's prestigious school leaver programme provides a route into investment banking, technology and operations, combining work experience with a professional qualification. Salary from £45,000 for higher-level programmes.",
    websiteUrl: "https://www.goldmansachs.com/careers/students/programs/school-leaver",
    russellGroup: false,
    ranking: null,
    entryRequirements: "A-levels AAA. Strong Maths at A-level preferred. Exceptional analytical ability required.",
    ucasPoints: 128,
    studentSatisfaction: 4.6,
    notableSubjects: ["Investment Banking", "Finance", "Technology", "Risk Management", "Operations"],
    facilities: ["London HQ", "Trading floors", "Technology labs", "Global network access"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-25", "2026-11-12"],
    applicationDeadline: "November 2026",
    applicationsOpen: "September 2026",
  },
  {
    name: "Penguin Random House Publishing Apprenticeship",
    type: "Apprenticeship Provider" as const,
    region: "London",
    city: "London",
    description: "Penguin Random House, the world's largest book publisher, offers apprenticeships in editorial, marketing, sales, rights and digital publishing from its London offices. Earn from £22,000 in a creative, passionate environment.",
    websiteUrl: "https://www.penguinrandomhouse.co.uk/opportunities/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade 4+. Passionate about books and the creative industries.",
    ucasPoints: null,
    studentSatisfaction: 4.5,
    notableSubjects: ["Editorial", "Marketing", "Digital Publishing", "Rights & Licensing", "Sales"],
    facilities: ["London offices", "Publishing library", "Creative studios", "Mentoring network"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-21", "2026-09-03"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },
  {
    name: "Transport for London Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "London",
    city: "London",
    description: "TfL offers apprenticeships in engineering, technology, operations and project management across its vast transport network. Earn from £25,000 with the opportunity to help shape London's transport future.",
    websiteUrl: "https://tfl.gov.uk/corporate/careers/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade 4+. GCSE Science or Engineering grade 4+ for technical routes.",
    ucasPoints: null,
    studentSatisfaction: 4.3,
    notableSubjects: ["Civil Engineering", "Electrical Engineering", "Project Management", "Data Analysis", "Business Operations"],
    facilities: ["Central London offices", "Underground depots", "Engineering workshops"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-04", "2026-10-15"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },

  // ── NORTHERN IRELAND ──────────────────────────────────────────────────────────
  {
    name: "Concentrix Technology Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Northern Ireland",
    city: "Belfast",
    description: "Concentrix, a global technology company with a major hub in Belfast, offers apprenticeships in IT, data, software development and business operations within Northern Ireland's growing tech sector. Salaries from £19,000.",
    websiteUrl: "https://careers.concentrix.com/apprenticeships-ni",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE English and Maths grade C+. Interest in technology and customer solutions.",
    ucasPoints: null,
    studentSatisfaction: 4.0,
    notableSubjects: ["Software Development", "Data Analysis", "IT Support", "Business Administration", "Cybersecurity"],
    facilities: ["Belfast city centre offices", "Technology training labs", "Collaboration spaces"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-28", "2026-09-24"],
    applicationDeadline: "Rolling intake",
    applicationsOpen: "Throughout the year",
  },
  {
    name: "Caterpillar NI Engineering Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "Northern Ireland",
    city: "Newtownabbey",
    description: "Caterpillar's Northern Ireland facilities manufacture precision components for construction equipment. Their engineering apprenticeships offer excellent training in advanced manufacturing and engineering. Salary from £19,000.",
    websiteUrl: "https://www.caterpillar.com/en/careers/apprenticeships.html",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths and English grade C+. GCSE Engineering or Science preferred.",
    ucasPoints: null,
    studentSatisfaction: 4.4,
    notableSubjects: ["Mechanical Engineering", "Manufacturing Engineering", "Quality Engineering", "CNC Machining"],
    facilities: ["Newtownabbey plant", "Training workshops", "CNC machining centres", "Quality labs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-11", "2026-10-22"],
    applicationDeadline: "February 2027",
    applicationsOpen: "September 2026",
  },

  // ── SOUTH EAST (additional) ───────────────────────────────────────────────────
  {
    name: "BAE Systems Apprenticeships",
    type: "Apprenticeship Provider" as const,
    region: "South East",
    city: "Farnborough",
    description: "BAE Systems, the UK's largest defence company, offers apprenticeships in aerospace engineering, software, cybersecurity and manufacturing across sites in Farnborough and beyond. Salary from £22,000. UK nationality required.",
    websiteUrl: "https://careers.baesystems.com/apprenticeships",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Maths and English grade 5+. A-levels in STEM subjects preferred. UK nationality required for most roles.",
    ucasPoints: 96,
    studentSatisfaction: 4.5,
    notableSubjects: ["Aerospace Engineering", "Cybersecurity", "Software Engineering", "Electronic Engineering", "Manufacturing"],
    facilities: ["Farnborough site", "Warton Aerodrome", "Testing facilities", "State-of-the-art labs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-25", "2026-10-08"],
    applicationDeadline: "January 2027",
    applicationsOpen: "September 2026",
  },
];

async function addApprenticeships() {
  console.log("Adding new apprenticeship providers...\n");

  const existing = await db.select({ name: institutionsTable.name }).from(institutionsTable);
  const existingNames = new Set(existing.map((i) => i.name));

  const toInsert = newProviders.filter((p) => !existingNames.has(p.name));

  if (toInsert.length === 0) {
    console.log("All apprenticeship providers already exist. Nothing to add.");
    process.exit(0);
  }

  console.log(`Adding ${toInsert.length} new apprenticeship providers...`);

  for (const provider of toInsert) {
    await db.insert(institutionsTable).values(provider);
    console.log(`  ✓ ${provider.name} (${provider.city}, ${provider.region})`);
  }

  console.log(`\nDone! Added ${toInsert.length} apprenticeship providers.`);
  process.exit(0);
}

addApprenticeships().catch((err) => {
  console.error("Failed:", err);
  process.exit(1);
});
