import { db, institutionsTable, eq } from "@workspace/db";

const industrialPlacements = [
  // ── LONDON ───────────────────────────────────────────────────────────────────
  {
    name: "Goldman Sachs Summer Insight",
    type: "Industrial Placement" as const,
    region: "London",
    city: "London",
    description: "Goldman Sachs runs structured summer insight and work experience programmes for Year 12 students exploring finance, technology and operations. The week-long programme includes workshops, desk shadowing and senior speaker sessions at the Bishopsgate office.",
    websiteUrl: "https://www.goldmansachs.com/careers/students/programs/emea/insight-programs.html",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12 A-Level students. Strong academic record. Interest in finance or technology.",
    ucasPoints: null,
    studentSatisfaction: 4.7,
    notableSubjects: ["Finance", "Economics", "Computer Science", "Data Science", "Business"],
    facilities: ["Bishopsgate HQ", "Trading floors", "Tech labs", "Conference suites"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-22", "2026-07-13"],
    applicationDeadline: "30 April 2026",
    applicationsOpen: "February 2026",
    featured: false,
  },
  {
    name: "JP Morgan Work Experience Programme",
    type: "Industrial Placement" as const,
    region: "London",
    city: "London",
    description: "JP Morgan's Spring Week and Summer Insight programmes give Year 12 and Year 13 students a first look at investment banking, technology and operations. Students attend skills workshops, networking events and business challenges over 5 days.",
    websiteUrl: "https://careers.jpmorgan.com/global/en/students/programs",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12 or Year 13. 3 A-Level predictions at ABB or above preferred. Open to all subjects.",
    ucasPoints: null,
    studentSatisfaction: 4.6,
    notableSubjects: ["Finance", "Economics", "Technology", "Business Management", "Data Analytics"],
    facilities: ["Canary Wharf offices", "London HQ", "Digital labs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-04-14", "2026-07-06"],
    applicationDeadline: "28 February 2026",
    applicationsOpen: "November 2025",
    featured: false,
  },
  {
    name: "NHS Work Experience — NHS England",
    type: "Industrial Placement" as const,
    region: "London",
    city: "London",
    description: "NHS England coordinates structured healthcare work experience placements for Year 10–13 students across hospitals, GP surgeries and community settings. Gain insight into medicine, nursing, allied health professions and NHS management. Available nationwide through local NHS trusts.",
    websiteUrl: "https://www.healthcareers.nhs.uk/career-planning/work-experience/work-experience-other-routes",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 10 (GCSE) or Year 12 (A-Level). DBS check required for clinical placements. Minimum grade 4 in English and Science.",
    ucasPoints: null,
    studentSatisfaction: 4.8,
    notableSubjects: ["Biology", "Chemistry", "Health and Social Care", "Psychology", "Physical Education"],
    facilities: ["Hospitals nationwide", "GP practices", "Mental health units", "Community health centres"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-04-20", "2026-07-06", "2026-10-26"],
    applicationDeadline: "Rolling — apply 3 months in advance",
    applicationsOpen: "Throughout the year",
    featured: false,
  },
  {
    name: "Transport for London Insight Placement",
    type: "Industrial Placement" as const,
    region: "London",
    city: "London",
    description: "TfL offers structured GCSE and A-Level work placements across engineering, digital, business and operations teams. Students gain hands-on experience in one of the world's largest urban transport systems, including Tube, Overground and Crossrail operations.",
    websiteUrl: "https://tfl.gov.uk/corporate/careers/early-careers",
    russellGroup: false,
    ranking: null,
    entryRequirements: "GCSE Year 10/11 or A-Level Year 12/13. Interest in engineering, digital or business.",
    ucasPoints: null,
    studentSatisfaction: 4.5,
    notableSubjects: ["Engineering", "Computer Science", "Business Studies", "Mathematics", "Environmental Science"],
    facilities: ["Palestra HQ Southwark", "Operational depots", "Control centres", "Engineering workshops"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-11", "2026-07-13", "2026-10-19"],
    applicationDeadline: "6 weeks before placement start",
    applicationsOpen: "February 2026",
    featured: false,
  },
  {
    name: "Deloitte Discovery Work Experience",
    type: "Industrial Placement" as const,
    region: "London",
    city: "London",
    description: "Deloitte's Discovery work experience programme is a 5-day virtual and in-person programme for Year 12 students, exploring audit, consulting, tax and technology. Students work on real business challenges and build professional skills alongside Deloitte partners.",
    websiteUrl: "https://www2.deloitte.com/uk/en/pages/careers/articles/school-leavers-experience.html",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12. Predicted 3 A-Levels at BBB. Open to all subjects.",
    ucasPoints: null,
    studentSatisfaction: 4.5,
    notableSubjects: ["Business Studies", "Economics", "Mathematics", "Computer Science", "Law"],
    facilities: ["New Street Square London", "12 UK offices", "Digital collaboration hubs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-04-07", "2026-06-29", "2026-11-02"],
    applicationDeadline: "Rolling — places limited",
    applicationsOpen: "January 2026",
    featured: false,
  },
  {
    name: "KPMG School Leaver Work Experience",
    type: "Industrial Placement" as const,
    region: "London",
    city: "London",
    description: "KPMG offers Spring Insight and Summer Experience programmes for Year 12 and GCSE students in audit, consulting, tax and technology. Includes office visits, case studies and mentoring from KPMG professionals across 20 UK offices.",
    websiteUrl: "https://www.kpmgcareers.co.uk/school-college-leavers/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 10–12. GCSE Maths and English grade 5+. No prior experience needed.",
    ucasPoints: null,
    studentSatisfaction: 4.4,
    notableSubjects: ["Mathematics", "Economics", "Business Studies", "Computer Science", "Law"],
    facilities: ["15 Canary Wharf London", "20 UK regional offices", "Innovation hubs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-04-21", "2026-07-07"],
    applicationDeadline: "31 March 2026",
    applicationsOpen: "January 2026",
    featured: false,
  },

  // ── SOUTH EAST ────────────────────────────────────────────────────────────────
  {
    name: "GSK (GlaxoSmithKline) STEM Placement",
    type: "Industrial Placement" as const,
    region: "South East",
    city: "Stevenage",
    description: "GSK offers Year 12 STEM insight weeks and T-Level industry placements at its UK R&D sites in Stevenage and Ware. Students work alongside scientists on real pharmaceutical research projects. T-Level placements run for 45 days across the academic year.",
    websiteUrl: "https://www.gsk.com/en-gb/careers/early-talent/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12 studying STEM A-Levels (Biology, Chemistry, Physics, Maths). Grade B minimum predicted. T-Level students also eligible.",
    ucasPoints: null,
    studentSatisfaction: 4.8,
    notableSubjects: ["Biology", "Chemistry", "Physics", "Mathematics", "Applied Science"],
    facilities: ["Stevenage R&D campus", "Ware site", "Modern laboratories", "Clinical manufacturing suites"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-22", "2026-09-14"],
    applicationDeadline: "31 March 2026",
    applicationsOpen: "January 2026",
    featured: false,
  },
  {
    name: "Unilever Future Leaders Lab",
    type: "Industrial Placement" as const,
    region: "South East",
    city: "Leatherhead",
    description: "Unilever's Future Leaders Lab gives Year 12 students a week-long immersive work experience at the Port Sunlight or Leatherhead R&D centres. Students join FMCG science and business teams working on product development, marketing and sustainability challenges.",
    websiteUrl: "https://careers.unilever.com/early-careers",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12. Any A-Level combination. Passion for sustainability and business.",
    ucasPoints: null,
    studentSatisfaction: 4.6,
    notableSubjects: ["Business Studies", "Chemistry", "Biology", "Environmental Science", "Design and Technology"],
    facilities: ["Leatherhead R&D centre", "Port Sunlight facility", "Product labs", "Sustainability hub"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-15", "2026-07-06"],
    applicationDeadline: "31 March 2026",
    applicationsOpen: "February 2026",
    featured: false,
  },
  {
    name: "Microsoft UK Work Experience",
    type: "Industrial Placement" as const,
    region: "South East",
    city: "Reading",
    description: "Microsoft UK offers week-long immersive work experience for Year 12 students at its Reading HQ. Students explore software engineering, cloud computing, AI and business. Includes coding workshops, team projects and presentations to Microsoft employees.",
    websiteUrl: "https://careers.microsoft.com/v2/global/en/uk-students.html",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12. Interest in technology essential. Studying Computer Science, Maths or Sciences preferred.",
    ucasPoints: null,
    studentSatisfaction: 4.7,
    notableSubjects: ["Computer Science", "Mathematics", "Physics", "Business Studies", "Engineering"],
    facilities: ["Thames Valley Park Reading", "Modern tech campus", "AI labs", "Collaboration spaces"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-08", "2026-07-13"],
    applicationDeadline: "28 February 2026",
    applicationsOpen: "November 2025",
    featured: false,
  },

  // ── MIDLANDS ─────────────────────────────────────────────────────────────────
  {
    name: "Jaguar Land Rover GCSE Work Experience",
    type: "Industrial Placement" as const,
    region: "Midlands",
    city: "Coventry",
    description: "JLR offers one-week engineering and design work experience placements for Year 10 and Year 12 students at its Coventry and Solihull sites. Students join teams in vehicle engineering, design studios, manufacturing and software development.",
    websiteUrl: "https://careers.jaguarlandrover.com/early-careers",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 10 (GCSE) or Year 12 (A-Level). Interest in engineering, design or computing. STEM subjects preferred.",
    ucasPoints: null,
    studentSatisfaction: 4.6,
    notableSubjects: ["Engineering", "Design and Technology", "Computer Science", "Mathematics", "Physics"],
    facilities: ["Coventry HQ", "Solihull manufacturing plant", "Design studios", "Engineering labs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-18", "2026-07-06", "2026-10-26"],
    applicationDeadline: "6 weeks before start",
    applicationsOpen: "March 2026",
    featured: false,
  },
  {
    name: "Severn Trent T-Level Placement",
    type: "Industrial Placement" as const,
    region: "Midlands",
    city: "Coventry",
    description: "Severn Trent offers T-Level industry placements for students studying Engineering, Digital and Environmental subjects. Students spend 45 days across the academic year working on real water management, infrastructure and digital transformation projects.",
    websiteUrl: "https://www.severntrent.com/about-us/our-people/early-careers/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "T-Level students in Engineering, Digital or Environmental subjects. GCSE Maths and English grade 4+.",
    ucasPoints: null,
    studentSatisfaction: 4.4,
    notableSubjects: ["Engineering", "Environmental Science", "Computer Science", "Applied Science", "Business Studies"],
    facilities: ["Coventry HQ", "Water treatment sites", "Digital centres", "Field operations"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-09-07", "2027-01-11"],
    applicationDeadline: "30 June 2026",
    applicationsOpen: "April 2026",
    featured: false,
  },

  // ── NORTH WEST ────────────────────────────────────────────────────────────────
  {
    name: "Siemens UK School Placement Programme",
    type: "Industrial Placement" as const,
    region: "North West",
    city: "Manchester",
    description: "Siemens UK offers structured GCSE and A-Level work experience across its engineering, digital and smart infrastructure divisions. Students work on real projects in electrification, automation and digitalization at Manchester and Congleton sites.",
    websiteUrl: "https://www.siemens.co.uk/en/company/jobs/early-careers.html",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 10–12. GCSE Maths and Physics grade 5+. T-Level placements also available.",
    ucasPoints: null,
    studentSatisfaction: 4.5,
    notableSubjects: ["Physics", "Engineering", "Computer Science", "Mathematics", "Applied Science"],
    facilities: ["Manchester Digital Hub", "Congleton engineering site", "Smart grid labs", "R&D centres"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-04", "2026-06-22", "2026-10-05"],
    applicationDeadline: "4 weeks before start",
    applicationsOpen: "February 2026",
    featured: false,
  },
  {
    name: "ITV Work Experience Programme",
    type: "Industrial Placement" as const,
    region: "North West",
    city: "Salford",
    description: "ITV offers creative and technical work experience at MediaCityUK Salford and its London studios. Year 12 students explore TV production, journalism, marketing, and digital media. Includes behind-the-scenes access to live shows and production teams.",
    websiteUrl: "https://careers.itv.com/early-careers/work-experience",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12. Any A-Level subjects. Strong interest in media, journalism or creative industries.",
    ucasPoints: null,
    studentSatisfaction: 4.6,
    notableSubjects: ["Media Studies", "Drama and Theatre Studies", "English Language", "Film Studies", "Computer Science"],
    facilities: ["MediaCityUK Salford", "London Waterhouse Square studios", "Broadcasting suites", "Production facilities"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-01", "2026-07-06"],
    applicationDeadline: "31 March 2026",
    applicationsOpen: "January 2026",
    featured: false,
  },

  // ── YORKSHIRE ────────────────────────────────────────────────────────────────
  {
    name: "GCHQ Cyber Discovery Placement",
    type: "Industrial Placement" as const,
    region: "Yorkshire",
    city: "Scarborough",
    description: "GCHQ offers structured insight days and work experience for A-Level students interested in cyber security, software engineering and intelligence analysis. Part of the CyberFirst programme, open to Year 12 and 13 students with strong STEM aptitude.",
    websiteUrl: "https://www.gchq-careers.co.uk/early-careers/schools-and-colleges/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12 or 13. UK national (security clearance required). Strong predicted grades in Computer Science, Maths or Physics.",
    ucasPoints: null,
    studentSatisfaction: 4.9,
    notableSubjects: ["Computer Science", "Mathematics", "Physics", "Further Mathematics", "Engineering"],
    facilities: ["GCHQ Scarborough site", "Cheltenham HQ", "Cyber labs", "Intelligence operations"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-08", "2026-07-13"],
    applicationDeadline: "28 February 2026",
    applicationsOpen: "November 2025",
    featured: false,
  },

  // ── SOUTH WEST ────────────────────────────────────────────────────────────────
  {
    name: "Airbus UK Work Experience",
    type: "Industrial Placement" as const,
    region: "South West",
    city: "Bristol",
    description: "Airbus UK runs GCSE and A-Level work experience at its Filton, Bristol site — home to wing design and engineering for the A380 and A350. Students join real engineering, manufacturing and digital teams for 1–2 weeks during school holidays.",
    websiteUrl: "https://www.airbus.com/en/careers/students-and-graduates",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 10 (GCSE) or Year 12 (A-Level). STEM subjects essential. GCSE Maths and Science grade 5+.",
    ucasPoints: null,
    studentSatisfaction: 4.7,
    notableSubjects: ["Physics", "Engineering", "Design and Technology", "Mathematics", "Computer Science"],
    facilities: ["Filton Bristol site", "Wing manufacturing plant", "Design labs", "Engineering test rigs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-04-13", "2026-07-27", "2026-10-26"],
    applicationDeadline: "8 weeks before start",
    applicationsOpen: "January 2026",
    featured: false,
  },

  // ── SCOTLAND ──────────────────────────────────────────────────────────────────
  {
    name: "BP STEM Schools Placement",
    type: "Industrial Placement" as const,
    region: "Scotland",
    city: "Aberdeen",
    description: "BP offers week-long Highers and A-Level STEM insight placements at its Aberdeen North Sea operations and Sunbury-on-Thames HQ. Students explore oil & gas engineering, renewable energy, data science and environmental science with professional mentors.",
    websiteUrl: "https://www.bp.com/en_gb/united-kingdom/home/work-with-us/students/work-experience.html",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12 (A-Level) or S5/S6 (Scottish Highers). STEM subjects. UK resident preferred for security reasons.",
    ucasPoints: null,
    studentSatisfaction: 4.5,
    notableSubjects: ["Chemistry", "Physics", "Environmental Science", "Mathematics", "Engineering"],
    facilities: ["Aberdeen North Sea hub", "Sunbury-on-Thames HQ", "Offshore operations", "Energy transition labs"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-15", "2026-07-13"],
    applicationDeadline: "31 March 2026",
    applicationsOpen: "January 2026",
    featured: false,
  },
  {
    name: "Scottish Government Civil Service Work Experience",
    type: "Industrial Placement" as const,
    region: "Scotland",
    city: "Edinburgh",
    description: "The Scottish Government offers structured work placements for S4–S6 and A-Level equivalent students across policy, digital, legal and communications teams. Part of the UK-wide Civil Service work experience scheme, running during school holidays.",
    websiteUrl: "https://www.civil-service-careers.gov.uk/early-careers/work-experience/",
    russellGroup: false,
    ranking: null,
    entryRequirements: "S4–S6 Scottish students or Year 11–13 for UK placements. No specific subject requirements. UK national.",
    ucasPoints: null,
    studentSatisfaction: 4.3,
    notableSubjects: ["Politics", "History", "Law", "Economics", "English Language"],
    facilities: ["St Andrew's House Edinburgh", "Victoria Quay", "Scottish Parliament area offices"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-04-13", "2026-07-20", "2026-10-19"],
    applicationDeadline: "6 weeks before placement",
    applicationsOpen: "Throughout the year",
    featured: false,
  },

  // ── EAST OF ENGLAND ───────────────────────────────────────────────────────────
  {
    name: "AstraZeneca T-Level Science Placement",
    type: "Industrial Placement" as const,
    region: "East of England",
    city: "Cambridge",
    description: "AstraZeneca's Cambridge Discovery Centre offers T-Level industry placements and Year 12 STEM insight weeks in drug discovery, oncology research and bioinformatics. Students work alongside world-class scientists on real pharmaceutical projects.",
    websiteUrl: "https://careers.astrazeneca.com/early-careers",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12 or T-Level students in Science or Applied Science. Grade B+ predicted in Biology and Chemistry.",
    ucasPoints: null,
    studentSatisfaction: 4.8,
    notableSubjects: ["Biology", "Chemistry", "Applied Science", "Mathematics", "Health and Social Care"],
    facilities: ["Cambridge Discovery Centre", "Macclesfield site", "Modern labs", "Bioinformatics suites"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-08", "2026-06-29"],
    applicationDeadline: "28 February 2026",
    applicationsOpen: "November 2025",
    featured: false,
  },

  // ── WALES ─────────────────────────────────────────────────────────────────────
  {
    name: "Admiral Group School Insight Week",
    type: "Industrial Placement" as const,
    region: "Wales",
    city: "Cardiff",
    description: "Admiral Group offers Year 12 insight weeks at its Cardiff HQ for students interested in insurance, data science, software engineering and business. Students complete real work challenges and hear from diverse role models across the business.",
    websiteUrl: "https://www.admiralgroup.co.uk/careers/early-careers",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 12. Any A-Level subjects. Interest in finance, technology or business.",
    ucasPoints: null,
    studentSatisfaction: 4.5,
    notableSubjects: ["Mathematics", "Business Studies", "Computer Science", "Economics", "Statistics"],
    facilities: ["Cardiff HQ", "Modern office campus", "Tech labs", "Collaboration spaces"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-06-22", "2026-07-13"],
    applicationDeadline: "30 April 2026",
    applicationsOpen: "February 2026",
    featured: false,
  },

  // ── NORTH EAST ────────────────────────────────────────────────────────────────
  {
    name: "Nissan UK Manufacturing Experience",
    type: "Industrial Placement" as const,
    region: "North East",
    city: "Sunderland",
    description: "Nissan's Sunderland plant — the UK's largest car factory — offers structured GCSE and A-Level work experience in manufacturing engineering, quality control, robotics and operations management. Includes factory floor access and engineering project work.",
    websiteUrl: "https://www.nissan.co.uk/about-nissan/nissan-in-the-uk/sunderland-plant.html",
    russellGroup: false,
    ranking: null,
    entryRequirements: "Year 10 (GCSE) or Year 12 (A-Level). STEM interest. GCSE Maths grade 4+.",
    ucasPoints: null,
    studentSatisfaction: 4.4,
    notableSubjects: ["Engineering", "Design and Technology", "Physics", "Mathematics", "Computer Science"],
    facilities: ["Sunderland manufacturing plant", "Robotics labs", "EV battery production", "Engineering workshops"],
    bursaries: false,
    internationalStudents: false,
    relatedCareers: [] as number[],
    annualFees: null,
    internationalFees: null,
    openDayDates: ["2026-05-11", "2026-07-06", "2026-10-12"],
    applicationDeadline: "6 weeks before start",
    applicationsOpen: "March 2026",
    featured: false,
  },
];

async function main() {
  console.log(`Seeding ${industrialPlacements.length} industrial placement providers...`);

  let inserted = 0;
  let skipped = 0;

  for (const placement of industrialPlacements) {
    const existing = await db
      .select({ id: institutionsTable.id })
      .from(institutionsTable)
      .where(eq(institutionsTable.name, placement.name))
      .limit(1);

    if (existing.length > 0) {
      console.log(`  ⏭  Skipping "${placement.name}" (already exists)`);
      skipped++;
      continue;
    }

    await db.insert(institutionsTable).values(placement);
    console.log(`  ✓  Inserted "${placement.name}"`);
    inserted++;
  }

  console.log(`\nDone: ${inserted} inserted, ${skipped} skipped.`);
}

main().catch(console.error);
