import { db, subjectsTable, careersTable, institutionsTable, routesTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(routesTable);
  await db.delete(institutionsTable);
  await db.delete(careersTable);
  await db.delete(subjectsTable);

  // ─── SUBJECTS ───────────────────────────────────────────────────────────────
  const subjectData = [
    {
      name: "Mathematics",
      level: "Both",
      category: "STEM",
      description: "The study of numbers, quantities, shapes, and patterns. Essential for many careers and higher education courses.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC", "Cambridge"],
      studyTips: [
        "Practice past papers regularly under timed conditions",
        "Make sure you understand the method, not just the answer",
        "Use a revision checklist to track topics covered",
        "Work through examples step-by-step and check your working",
        "Don't skip algebra — it underpins most topics",
      ],
      keyTopics: ["Algebra", "Number", "Geometry", "Statistics", "Probability", "Calculus (A-Level)", "Mechanics (A-Level)"],
      assessmentStructure: "GCSE: 3 papers (1 non-calculator, 2 calculator). A-Level: 3 papers including Pure, Statistics, and Mechanics.",
      usefulResources: [
        { name: "Maths Genie", url: "https://www.mathsgenie.co.uk", type: "Website" },
        { name: "BBC Bitesize Maths", url: "https://www.bbc.co.uk/bitesize/subjects/z38pycw", type: "Website" },
        { name: "Corbettmaths", url: "https://corbettmaths.com", type: "Practice Questions" },
        { name: "Exam Solutions", url: "https://www.examsolutions.net", type: "Video" },
      ],
      relatedCareers: [],
    },
    {
      name: "English Language",
      level: "GCSE",
      category: "Humanities",
      description: "Develops reading, writing, and communication skills through analysis of language and production of varied text types.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Read widely — newspapers, novels, non-fiction",
        "Practise writing in different styles (persuasive, narrative, descriptive)",
        "Learn quotation analysis using PEEL structure",
        "Build your vocabulary with a word journal",
      ],
      keyTopics: ["Reading and analysis", "Creative writing", "Transactional writing", "Language and structure"],
      assessmentStructure: "Two written exams. Component 1: Creative reading and writing. Component 2: Writers' viewpoints and perspectives.",
      usefulResources: [
        { name: "BBC Bitesize English", url: "https://www.bbc.co.uk/bitesize/subjects/z3kw2hv", type: "Website" },
        { name: "Mr Bruff YouTube", url: "https://www.youtube.com/mrbruff", type: "Video" },
      ],
      relatedCareers: [],
    },
    {
      name: "English Literature",
      level: "Both",
      category: "Humanities",
      description: "Study of poetry, prose, and drama across different periods and cultures, developing analytical and critical thinking skills.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Know your set texts inside out — annotate your copies",
        "Practise timed essay writing",
        "Explore context and how it shapes meaning",
        "Compare texts for theme, structure and language",
      ],
      keyTopics: ["Poetry anthology", "Modern novels", "Shakespeare", "19th-century literature", "Comparative essay skills"],
      assessmentStructure: "GCSE: Two written exams. A-Level: Written exams plus coursework component.",
      usefulResources: [
        { name: "Sparknotes", url: "https://www.sparknotes.com", type: "Website" },
        { name: "Litcharts", url: "https://www.litcharts.com", type: "Website" },
        { name: "Mr Salles Teaches English", url: "https://youtube.com", type: "Video" },
      ],
      relatedCareers: [],
    },
    {
      name: "Biology",
      level: "Both",
      category: "STEM",
      description: "The scientific study of living organisms, from cells to ecosystems, covering anatomy, genetics, evolution, and ecology.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC", "Cambridge"],
      studyTips: [
        "Create detailed mind maps for each topic",
        "Use mnemonics for long lists (e.g. cell organelles)",
        "Practise 6-mark extended response questions",
        "Draw and label diagrams from memory",
        "Review required practicals carefully",
      ],
      keyTopics: ["Cell biology", "Organisation", "Genetics and evolution", "Ecology", "Homeostasis", "Nervous system", "Photosynthesis and respiration"],
      assessmentStructure: "GCSE: 2-3 papers depending on board. A-Level: 3 written papers plus practical endorsement.",
      usefulResources: [
        { name: "Biology Corner", url: "https://biologycorner.com", type: "Website" },
        { name: "BBC Bitesize Biology", url: "https://www.bbc.co.uk/bitesize/subjects/z9ddmp3", type: "Website" },
        { name: "Freesciencelessons YouTube", url: "https://youtube.com", type: "Video" },
      ],
      relatedCareers: [],
    },
    {
      name: "Chemistry",
      level: "Both",
      category: "STEM",
      description: "Study of matter, its properties, and the changes it undergoes. Covers atomic structure, bonding, reactions, and organic chemistry.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Learn equations and constants — write them from memory",
        "Practise calculation questions with unit conversions",
        "Understand mechanisms (not just steps) in organic chemistry",
        "Use flashcards for definitions and facts",
      ],
      keyTopics: ["Atomic structure", "Bonding", "Quantitative chemistry", "Organic chemistry", "Thermodynamics", "Equilibria", "Electrochemistry"],
      assessmentStructure: "GCSE: 2-3 papers. A-Level: 3 written papers including practicals paper.",
      usefulResources: [
        { name: "Chemrevise", url: "https://chemrevise.org", type: "Revision Guide" },
        { name: "Freesciencelessons YouTube", url: "https://youtube.com", type: "Video" },
        { name: "RSC Learn Chemistry", url: "https://rsc.org/learn-chemistry", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "Physics",
      level: "Both",
      category: "STEM",
      description: "Study of matter, energy, and the fundamental forces of nature. Covers mechanics, waves, electricity, and modern physics.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Know all the equations — make a formula sheet",
        "Work through past papers and mark schemes",
        "Draw clear free body diagrams for mechanics",
        "Understand the physics behind the maths",
      ],
      keyTopics: ["Forces and motion", "Energy", "Waves and optics", "Electricity and magnetism", "Particle physics", "Quantum mechanics (A-Level)"],
      assessmentStructure: "GCSE: 2-3 papers. A-Level: 3 papers including practical assessment.",
      usefulResources: [
        { name: "Physics & Maths Tutor", url: "https://www.physicsandmathstutor.com", type: "Past Papers" },
        { name: "BBC Bitesize Physics", url: "https://bbc.co.uk/bitesize/subjects/zng4d2p", type: "Website" },
        { name: "Isaac Physics", url: "https://isaacphysics.org", type: "Practice Questions" },
      ],
      relatedCareers: [],
    },
    {
      name: "Computer Science",
      level: "Both",
      category: "STEM",
      description: "Covers computational thinking, programming, algorithms, data structures, networking, and cybersecurity.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Code regularly — apply theory in practice",
        "Understand algorithms and trace through code manually",
        "Use pseudocode and flowcharts to plan solutions",
        "Study binary, hex, and logic gates thoroughly",
      ],
      keyTopics: ["Programming fundamentals", "Algorithms and data structures", "Computer systems", "Networks and cybersecurity", "Databases (A-Level)", "Theory of computation (A-Level)"],
      assessmentStructure: "GCSE: 2 written papers + programming project. A-Level: 2-3 written papers + NEA project.",
      usefulResources: [
        { name: "Craig and Dave YouTube", url: "https://youtube.com", type: "Video" },
        { name: "BBC Bitesize Computer Science", url: "https://bbc.co.uk/bitesize/subjects/z34k7ty", type: "Website" },
        { name: "Raspberry Pi Foundation", url: "https://raspberrypi.org", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "History",
      level: "Both",
      category: "Humanities",
      description: "Critical study of the past through sources and evidence. Develops analytical writing, empathy, and understanding of change over time.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Learn key dates and events for each topic",
        "Practise source analysis using HCAP/HAPS frameworks",
        "Write structured essays with clear arguments",
        "Understand causation, consequence, significance, and change",
      ],
      keyTopics: ["British history", "World history", "Source analysis", "Historical interpretations", "Thematic studies"],
      assessmentStructure: "GCSE: 2-3 written papers. A-Level: 3 papers including independent coursework.",
      usefulResources: [
        { name: "History Learning Site", url: "https://www.historylearningsite.co.uk", type: "Website" },
        { name: "BBC History", url: "https://bbc.co.uk/history", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "Geography",
      level: "Both",
      category: "Humanities",
      description: "Study of physical and human environments, covering climate, ecosystems, urbanisation, development, and sustainability.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Learn case studies with specific named examples",
        "Practise map skills and data interpretation",
        "Structure exam answers using relevant geographical terminology",
        "Fieldwork prepares you well — understand your own data",
      ],
      keyTopics: ["Physical geography", "Human geography", "Fieldwork", "Climate change", "Development", "Hazards", "Tectonics"],
      assessmentStructure: "GCSE: 3 written papers including fieldwork. A-Level: 3 papers plus independent investigation.",
      usefulResources: [
        { name: "Internet Geography", url: "https://internetgeography.net", type: "Website" },
        { name: "Cool Geography", url: "https://www.coolgeography.co.uk", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "Psychology",
      level: "A-Level",
      category: "Social Sciences",
      description: "Scientific study of human and animal behaviour and mental processes. Covers research methods, social influence, memory, and abnormal psychology.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Learn all key studies (name, date, method, findings, evaluation)",
        "Use GRAVE or similar frameworks for evaluating research",
        "Apply psychological concepts to real-world scenarios",
        "Revise research methods thoroughly — worth many marks",
      ],
      keyTopics: ["Social influence", "Memory", "Attachment", "Psychopathology", "Biopsychology", "Research methods", "Cognition and development"],
      assessmentStructure: "A-Level: 3 written papers covering core studies, applications, and issues & debates.",
      usefulResources: [
        { name: "Simply Psychology", url: "https://simplypsychology.org", type: "Website" },
        { name: "Tutor2u Psychology", url: "https://tutor2u.net/psychology", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "Economics",
      level: "A-Level",
      category: "Social Sciences",
      description: "Study of how individuals, firms, and governments make decisions about allocating scarce resources.",
      examBoards: ["AQA", "Edexcel", "OCR"],
      studyTips: [
        "Practise drawing and interpreting economic diagrams",
        "Evaluate with both sides — advantages and disadvantages",
        "Read The Economist or FT to see theory in practice",
        "Learn key concepts: elasticity, market failure, fiscal/monetary policy",
      ],
      keyTopics: ["Supply and demand", "Market structures", "Macroeconomics", "International trade", "Government intervention", "Labour markets"],
      assessmentStructure: "A-Level: 3 written papers covering micro, macro, and themes.",
      usefulResources: [
        { name: "Tutor2u Economics", url: "https://tutor2u.net/economics", type: "Website" },
        { name: "Econplusdal YouTube", url: "https://youtube.com", type: "Video" },
      ],
      relatedCareers: [],
    },
    {
      name: "Business Studies",
      level: "Both",
      category: "Social Sciences",
      description: "How businesses operate, are managed, and make decisions. Covers marketing, finance, operations, and human resources.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Use real business case studies as examples in answers",
        "Practise financial calculations (profit, break-even, ratios)",
        "Structure evaluation answers with justified conclusions",
        "Follow business news to support case study answers",
      ],
      keyTopics: ["Marketing", "Finance", "Operations management", "Human resources", "Business strategy", "Globalisation"],
      assessmentStructure: "GCSE: 2 written papers. A-Level: 3 written papers.",
      usefulResources: [
        { name: "Tutor2u Business", url: "https://tutor2u.net/business", type: "Website" },
        { name: "BBC Business News", url: "https://bbc.co.uk/news/business", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "Art and Design",
      level: "Both",
      category: "Creative Arts",
      description: "Development of creative and artistic skills through practical work and critical analysis of artists and movements.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Build a strong sketchbook that shows your development process",
        "Research artists and link their techniques to your own work",
        "Practise exam prep piece under timed conditions",
        "Write clear annotations explaining your creative choices",
      ],
      keyTopics: ["Drawing and painting", "Mixed media", "Digital art", "Art history", "Contextual studies", "Personal project"],
      assessmentStructure: "GCSE: Portfolio (60%) + Externally set assignment with 10-hour exam (40%). A-Level: Similar but with critical and contextual studies unit.",
      usefulResources: [
        { name: "GCSE Pod Art", url: "https://www.gcsepod.com", type: "Website" },
        { name: "Tate Learning", url: "https://tate.org.uk/learn", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "French",
      level: "Both",
      category: "Languages",
      description: "Communication in French through listening, speaking, reading, and writing across a range of topics and contexts.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Listen to French radio, podcasts or TV daily",
        "Learn vocabulary in themed groups",
        "Practise speaking out loud — record yourself",
        "Use Anki or Quizlet for spaced repetition vocabulary",
      ],
      keyTopics: ["Identity and culture", "Local area and holidays", "School and future plans", "Global issues (GCSE)", "Literature and film (A-Level)"],
      assessmentStructure: "GCSE: 4 papers (listening, speaking, reading, writing). A-Level: Writing, speaking, and essay papers.",
      usefulResources: [
        { name: "Duolingo French", url: "https://duolingo.com", type: "Website" },
        { name: "BBC Languages French", url: "https://bbc.co.uk/languages", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "Music",
      level: "Both",
      category: "Creative Arts",
      description: "Study of music through performance, composition, and critical listening. Covers music history, theory, and analysis.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Practise your instrument or voice daily",
        "Listen carefully to set works with the score in front of you",
        "Learn music theory — it supports everything",
        "Record practice performances and critique them",
      ],
      keyTopics: ["Performance", "Composition", "Music history and context", "Listening and appraising", "Set works analysis"],
      assessmentStructure: "GCSE: Performance (30%), Composition (30%), Listening exam (40%). A-Level: Similar but more depth.",
      usefulResources: [
        { name: "ABRSM Theory", url: "https://abrsm.org", type: "Website" },
        { name: "musictheory.net", url: "https://musictheory.net", type: "Practice Questions" },
      ],
      relatedCareers: [],
    },
    {
      name: "Physical Education",
      level: "Both",
      category: "Sport & Health",
      description: "Theory and practical study of sport, exercise science, health, and performance.",
      examBoards: ["AQA", "Edexcel", "OCR", "WJEC"],
      studyTips: [
        "Link theory to your own performance experience",
        "Learn anatomy and physiology thoroughly",
        "Use diagrams and movement analysis in answers",
        "Keep a performance portfolio with evidence",
      ],
      keyTopics: ["Applied anatomy and physiology", "Exercise physiology", "Biomechanics", "Sport psychology", "Socio-cultural issues", "Practical performance"],
      assessmentStructure: "GCSE: 60% written exams + 40% practical performance. A-Level: Written exams + NEA performance and written analysis.",
      usefulResources: [
        { name: "Tutor2u PE", url: "https://tutor2u.net/pe", type: "Website" },
        { name: "PE Scholar", url: "https://pescholar.co.uk", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "Sociology",
      level: "A-Level",
      category: "Social Sciences",
      description: "Study of society, social institutions, and social inequality. Covers education, crime, families, and sociological theory.",
      examBoards: ["AQA", "OCR", "Edexcel"],
      studyTips: [
        "Learn key sociologists and their arguments",
        "Apply perspectives (Functionalism, Marxism, Feminism) to each topic",
        "Use specific studies as evidence in essays",
        "Practise structured essays with clear introductions and conclusions",
      ],
      keyTopics: ["Education", "Crime and deviance", "Families and households", "Social stratification", "Sociological theories and methods", "Globalisation"],
      assessmentStructure: "A-Level: 3 written papers covering core topics, theory, and methods.",
      usefulResources: [
        { name: "Sociology Guide", url: "https://sociologyguide.com", type: "Website" },
        { name: "Tutor2u Sociology", url: "https://tutor2u.net/sociology", type: "Website" },
      ],
      relatedCareers: [],
    },
    {
      name: "Law",
      level: "A-Level",
      category: "Humanities",
      description: "Introduction to the English legal system, including contract law, criminal law, tort, and legal personnel.",
      examBoards: ["AQA", "OCR", "WJEC"],
      studyTips: [
        "Learn key cases with facts, decision, and legal principle",
        "Apply IRAC method (Issue, Rule, Application, Conclusion)",
        "Practise scenario-based questions",
        "Follow legal news and landmark judgements",
      ],
      keyTopics: ["English legal system", "Criminal law", "Contract law", "Tort law", "Human rights", "Legal personnel"],
      assessmentStructure: "A-Level: 3 written papers covering substantive law and the English legal system.",
      usefulResources: [
        { name: "LAW Teacher", url: "https://lawteacher.net", type: "Website" },
        { name: "E-Law Resources", url: "https://e-lawresources.co.uk", type: "Website" },
      ],
      relatedCareers: [],
    },
  ];

  const insertedSubjects = await db.insert(subjectsTable).values(subjectData).returning();
  console.log(`Inserted ${insertedSubjects.length} subjects`);

  const subjectMap = Object.fromEntries(insertedSubjects.map((s) => [s.name, s.id]));

  // ─── CAREERS ────────────────────────────────────────────────────────────────
  const careerData = [
    {
      title: "Doctor (GP / Hospital)",
      sector: "Healthcare",
      description: "Diagnose and treat illness, injuries, and health conditions. GPs manage ongoing care; hospital doctors specialise in specific areas.",
      averageSalaryMin: 35000,
      averageSalaryMax: 110000,
      requiredSubjects: [subjectMap["Biology"], subjectMap["Chemistry"]],
      preferredSubjects: [subjectMap["Mathematics"], subjectMap["Physics"]],
      entryRoutes: ["University (Medicine degree)", "Graduate entry medicine"],
      requiredQualifications: ["A-levels: Biology + Chemistry + one other (often Maths/Physics)", "Medicine degree (5-6 years)", "Foundation Training (2 years)", "Specialty Training"],
      jobOutlook: "Excellent",
      workplaces: ["NHS hospitals", "GP surgeries", "Private clinics", "Research institutions"],
      dayInTheLife: "A hospital doctor's day involves ward rounds, consultations, reviewing test results, performing procedures, attending MDT meetings, and documenting patient notes.",
      relatedCareers: [],
    },
    {
      title: "Software Engineer",
      sector: "Technology",
      description: "Design, build, and maintain software applications, systems, and platforms. Work across web, mobile, desktop, and embedded systems.",
      averageSalaryMin: 35000,
      averageSalaryMax: 90000,
      requiredSubjects: [subjectMap["Computer Science"], subjectMap["Mathematics"]],
      preferredSubjects: [subjectMap["Physics"]],
      entryRoutes: ["University (Computer Science/Software Engineering)", "Degree Apprenticeship", "Bootcamp + self-study", "Higher Apprenticeship"],
      requiredQualifications: ["GCSE Maths grade 5+", "A-Level Computer Science or Maths preferred", "BSc Computer Science (or related) or equivalent experience"],
      jobOutlook: "Excellent",
      workplaces: ["Tech startups", "FAANG companies", "Banks and fintech", "Government digital services", "Any industry with a tech team"],
      dayInTheLife: "A typical day involves writing and reviewing code, attending stand-up meetings, debugging issues, collaborating with designers and product managers, and deploying new features.",
      relatedCareers: [],
    },
    {
      title: "Civil Engineer",
      sector: "Engineering",
      description: "Design, build, and maintain infrastructure including roads, bridges, dams, tunnels, and water systems.",
      averageSalaryMin: 28000,
      averageSalaryMax: 70000,
      requiredSubjects: [subjectMap["Mathematics"], subjectMap["Physics"]],
      preferredSubjects: [subjectMap["Chemistry"], subjectMap["Geography"]],
      entryRoutes: ["University (Civil Engineering)", "Degree Apprenticeship", "Higher Apprenticeship", "HNC/HND route"],
      requiredQualifications: ["A-Levels: Maths + Physics essential", "BEng or MEng Civil Engineering", "ICE graduate membership", "Chartered Engineer (CEng) status"],
      jobOutlook: "Good",
      workplaces: ["Construction firms", "Local authorities", "Network Rail", "Highways England", "Consultancies like Arup and WSP"],
      dayInTheLife: "Reviewing structural designs, visiting construction sites, running calculations, meeting with clients, drawing up plans in CAD software, and solving practical engineering challenges.",
      relatedCareers: [],
    },
    {
      title: "Solicitor",
      sector: "Law",
      description: "Provide legal advice and representation to individuals, companies, and organisations across areas such as property, employment, corporate, and criminal law.",
      averageSalaryMin: 27000,
      averageSalaryMax: 100000,
      requiredSubjects: [subjectMap["English Literature"], subjectMap["History"]],
      preferredSubjects: [subjectMap["Law"], subjectMap["Economics"]],
      entryRoutes: ["University (Law or non-law degree) + SQE", "Solicitor Apprenticeship (Level 7)", "Legal Exec route"],
      requiredQualifications: ["2 A-levels (any subject)", "Law degree or GDL + SQE exams (from 2021)", "Training contract (2 years)"],
      jobOutlook: "Good",
      workplaces: ["Law firms (Magic Circle to high street)", "In-house legal teams", "Government legal service", "Charities and NGOs"],
      dayInTheLife: "Advising clients, drafting legal documents, researching case law, attending court or tribunals, and negotiating on behalf of clients.",
      relatedCareers: [],
    },
    {
      title: "Nurse",
      sector: "Healthcare",
      description: "Provide care, support, and treatment to patients in hospitals, clinics, care homes, and the community.",
      averageSalaryMin: 28000,
      averageSalaryMax: 55000,
      requiredSubjects: [subjectMap["Biology"], subjectMap["Chemistry"]],
      preferredSubjects: [subjectMap["Psychology"], subjectMap["Sociology"]],
      entryRoutes: ["University (Nursing degree)", "Nursing Degree Apprenticeship", "Nursing Associate route"],
      requiredQualifications: ["GCSE English and Maths grade 4+", "A-Levels or equivalent (Biology preferred)", "BSc Nursing (3 years) or equivalent"],
      jobOutlook: "Excellent",
      workplaces: ["NHS hospitals", "GP surgeries", "Care homes", "Schools", "District nursing", "Prisons"],
      dayInTheLife: "Administering medication, taking observations, supporting patients with daily care, communicating with doctors, updating patient records, and comforting patients and families.",
      relatedCareers: [],
    },
    {
      title: "Financial Analyst",
      sector: "Finance",
      description: "Analyse financial data to guide investment decisions, business strategy, and risk management for companies and clients.",
      averageSalaryMin: 30000,
      averageSalaryMax: 80000,
      requiredSubjects: [subjectMap["Mathematics"], subjectMap["Economics"]],
      preferredSubjects: [subjectMap["Business Studies"], subjectMap["Computer Science"]],
      entryRoutes: ["University (Finance, Economics, Maths)", "School Leaver Programme", "Degree Apprenticeship"],
      requiredQualifications: ["A-Levels including Maths", "BSc Finance, Economics, or Mathematics", "CFA or ACCA qualification advantageous"],
      jobOutlook: "Good",
      workplaces: ["Investment banks", "Asset management firms", "Corporate finance teams", "Accounting firms"],
      dayInTheLife: "Building financial models, analysing market trends, preparing reports, attending client meetings, and working closely with senior analysts and portfolio managers.",
      relatedCareers: [],
    },
    {
      title: "Teacher",
      sector: "Education",
      description: "Plan and deliver lessons to pupils in primary or secondary schools, supporting their academic, social, and emotional development.",
      averageSalaryMin: 28000,
      averageSalaryMax: 65000,
      requiredSubjects: [],
      preferredSubjects: [subjectMap["English Literature"], subjectMap["Mathematics"], subjectMap["Biology"]],
      entryRoutes: ["University (Education degree)", "PGCE (postgraduate)", "School Direct", "Teach First (graduate programme)", "Apprenticeship"],
      requiredQualifications: ["GCSE English and Maths grade 4+", "Degree in any subject", "QTS (Qualified Teacher Status)"],
      jobOutlook: "Good",
      workplaces: ["State secondary schools", "Academy trusts", "Independent schools", "Sixth form colleges", "Special schools"],
      dayInTheLife: "Teaching lessons, marking work, planning lessons, attending staff meetings, supporting students with pastoral needs, and communicating with parents.",
      relatedCareers: [],
    },
    {
      title: "Graphic Designer",
      sector: "Creative Arts",
      description: "Create visual concepts to communicate ideas through digital and print media including branding, advertising, and publications.",
      averageSalaryMin: 22000,
      averageSalaryMax: 55000,
      requiredSubjects: [subjectMap["Art and Design"]],
      preferredSubjects: [subjectMap["Computer Science"], subjectMap["Business Studies"]],
      entryRoutes: ["University (Graphic Design, Visual Communication)", "Foundation Art Diploma + Degree", "Higher Apprenticeship", "Portfolio-based entry"],
      requiredQualifications: ["Art A-Level or equivalent", "BA Graphic Design", "Strong portfolio"],
      jobOutlook: "Moderate",
      workplaces: ["Creative agencies", "Marketing departments", "Publishing houses", "Freelance", "Tech companies"],
      dayInTheLife: "Creating visual designs in Adobe Suite, attending client briefs, presenting concepts, revising work based on feedback, and collaborating with copywriters and marketing teams.",
      relatedCareers: [],
    },
    {
      title: "Psychologist",
      sector: "Healthcare",
      description: "Study and apply knowledge of the mind and behaviour to help individuals improve their mental health, learning, and wellbeing.",
      averageSalaryMin: 31000,
      averageSalaryMax: 75000,
      requiredSubjects: [subjectMap["Psychology"], subjectMap["Biology"]],
      preferredSubjects: [subjectMap["Sociology"], subjectMap["Mathematics"]],
      entryRoutes: ["University (Psychology degree) + postgraduate training", "Degree Apprenticeship (emerging)"],
      requiredQualifications: ["A-Levels including Psychology or Biology", "BSc Psychology (BPS accredited)", "Doctorate in Clinical Psychology (DClinPsy) for NHS roles"],
      jobOutlook: "Excellent",
      workplaces: ["NHS mental health services", "Schools", "Prisons", "Charities", "Private practice", "Research institutions"],
      dayInTheLife: "Conducting assessments, delivering therapy sessions (CBT, DBT etc.), writing reports, collaborating with MDTs, and attending supervision and CPD training.",
      relatedCareers: [],
    },
    {
      title: "Environmental Scientist",
      sector: "Science",
      description: "Study and address environmental issues including pollution, climate change, biodiversity, and resource management.",
      averageSalaryMin: 25000,
      averageSalaryMax: 55000,
      requiredSubjects: [subjectMap["Biology"], subjectMap["Chemistry"]],
      preferredSubjects: [subjectMap["Geography"], subjectMap["Mathematics"]],
      entryRoutes: ["University (Environmental Science, Ecology, Geography)", "Higher Apprenticeship"],
      requiredQualifications: ["A-Levels in sciences/geography", "BSc Environmental Science or related degree", "Relevant certifications (IEMA, RSB)"],
      jobOutlook: "Excellent",
      workplaces: ["Environmental consultancies", "Government agencies (EA, Natural England)", "NGOs", "Research institutions", "Energy companies"],
      dayInTheLife: "Conducting field surveys, analysing data, writing environmental impact assessments, advising on planning applications, and reporting to clients or regulatory bodies.",
      relatedCareers: [],
    },
    {
      title: "Musician / Performer",
      sector: "Creative Arts",
      description: "Create and perform music professionally across genres including classical, jazz, pop, and session work.",
      averageSalaryMin: 18000,
      averageSalaryMax: 60000,
      requiredSubjects: [subjectMap["Music"]],
      preferredSubjects: [subjectMap["English Literature"]],
      entryRoutes: ["Conservatoire (specialist music training)", "University (Music degree)", "Independent route with auditions"],
      requiredQualifications: ["A-Level Music or equivalent", "ABRSM/Trinity grades", "Conservatoire or university degree", "Strong performance portfolio"],
      jobOutlook: "Moderate",
      workplaces: ["Orchestras", "Recording studios", "Theatres and West End", "Touring", "Schools and teaching", "Freelance"],
      dayInTheLife: "Practising instrument, attending rehearsals, performing concerts, recording sessions, teaching private lessons, managing bookings, and self-promotion.",
      relatedCareers: [],
    },
    {
      title: "Sports Coach / PE Teacher",
      sector: "Education",
      description: "Develop and improve athletes' performance and physical capabilities, or deliver PE lessons in schools.",
      averageSalaryMin: 22000,
      averageSalaryMax: 50000,
      requiredSubjects: [subjectMap["Physical Education"], subjectMap["Biology"]],
      preferredSubjects: [subjectMap["Psychology"]],
      entryRoutes: ["University (Sports Science, PE with QTS)", "PGCE PE", "NGB coaching qualifications route"],
      requiredQualifications: ["A-Levels in PE/Biology", "BSc Sports Science or BA PE", "Coaching qualifications (FA, LTA, UKA etc.)", "DBS check required"],
      jobOutlook: "Good",
      workplaces: ["Secondary schools", "Sports clubs and academies", "Leisure centres", "National governing bodies", "Elite sports teams"],
      dayInTheLife: "Planning and delivering training sessions, coaching athletes through competitions, monitoring performance data, attending matches, and supporting athlete welfare.",
      relatedCareers: [],
    },
    {
      title: "Data Scientist",
      sector: "Technology",
      description: "Analyse large datasets to extract insights and build predictive models to guide business and research decisions.",
      averageSalaryMin: 40000,
      averageSalaryMax: 95000,
      requiredSubjects: [subjectMap["Mathematics"], subjectMap["Computer Science"]],
      preferredSubjects: [subjectMap["Physics"], subjectMap["Economics"]],
      entryRoutes: ["University (Data Science, Computer Science, Statistics, Maths)", "Degree Apprenticeship", "Bootcamp + masters"],
      requiredQualifications: ["Strong A-Level Maths", "BSc in quantitative subject", "Proficiency in Python/R/SQL", "MSc Data Science (advantageous)"],
      jobOutlook: "Excellent",
      workplaces: ["Tech companies", "Healthcare", "Finance", "Government", "Retail and ecommerce", "Consulting"],
      dayInTheLife: "Cleaning and analysing data, building machine learning models, creating dashboards and visualisations, presenting findings to stakeholders, and collaborating with engineers.",
      relatedCareers: [],
    },
    {
      title: "Pharmacist",
      sector: "Healthcare",
      description: "Dispense medications, advise patients and healthcare professionals on drug use, and ensure safe and effective medicine management.",
      averageSalaryMin: 35000,
      averageSalaryMax: 65000,
      requiredSubjects: [subjectMap["Chemistry"], subjectMap["Biology"]],
      preferredSubjects: [subjectMap["Mathematics"]],
      entryRoutes: ["University (MPharm degree)", "Degree Apprenticeship (emerging)"],
      requiredQualifications: ["A-Levels: Chemistry + Biology/Maths", "MPharm (4 years)", "Pre-registration training (1 year)", "GPhC registration"],
      jobOutlook: "Good",
      workplaces: ["Community pharmacies (Boots, Lloyds)", "NHS hospitals", "GP practices", "Research and pharmaceutical industry"],
      dayInTheLife: "Dispensing prescriptions, counselling patients, checking for drug interactions, supporting GPs on medication reviews, and managing pharmacy stock.",
      relatedCareers: [],
    },
  ];

  const insertedCareers = await db.insert(careersTable).values(careerData).returning();
  console.log(`Inserted ${insertedCareers.length} careers`);

  // ─── INSTITUTIONS ────────────────────────────────────────────────────────────
  const institutionData = [
    {
      name: "University of Oxford",
      type: "University",
      region: "South East",
      city: "Oxford",
      description: "One of the world's leading universities, offering tutorial-based learning across sciences, humanities, and social sciences.",
      websiteUrl: "https://ox.ac.uk",
      russellGroup: true,
      ranking: 1,
      entryRequirements: "A*A*A to AAA depending on course. Entrance tests and interview required.",
      ucasPoints: null,
      studentSatisfaction: 4.5,
      notableSubjects: ["Medicine", "Law", "PPE", "Computer Science", "Engineering", "History"],
      facilities: ["Bodleian Libraries", "Oxford Union", "Colleges system", "Research labs"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[0].id, insertedCareers[3].id],
    },
    {
      name: "University of Cambridge",
      type: "University",
      region: "East of England",
      city: "Cambridge",
      description: "World-class university known for research excellence and the collegiate system. Strong STEM and humanities provision.",
      websiteUrl: "https://cam.ac.uk",
      russellGroup: true,
      ranking: 2,
      entryRequirements: "A*A*A to AAA depending on course. Entrance tests and interviews required.",
      ucasPoints: null,
      studentSatisfaction: 4.5,
      notableSubjects: ["Natural Sciences", "Mathematics", "Engineering", "Computer Science", "Law", "Medicine"],
      facilities: ["King's College Chapel", "Cavendish Laboratory", "University Library", "Sports grounds"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[0].id, insertedCareers[2].id, insertedCareers[12].id],
    },
    {
      name: "Imperial College London",
      type: "University",
      region: "London",
      city: "London",
      description: "Specialist science, engineering, and business university ranked among the world's best for STEM subjects.",
      websiteUrl: "https://imperial.ac.uk",
      russellGroup: true,
      ranking: 3,
      entryRequirements: "A*AA to AAA. Science A-Levels typically required.",
      ucasPoints: null,
      studentSatisfaction: 4.3,
      notableSubjects: ["Engineering", "Medicine", "Physics", "Computer Science", "Mathematics", "Business"],
      facilities: ["Hammersmith Hospital campus", "Innovation Hub", "Sports centre"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[1].id, insertedCareers[2].id, insertedCareers[5].id],
    },
    {
      name: "University of Edinburgh",
      type: "University",
      region: "Scotland",
      city: "Edinburgh",
      description: "One of the UK's oldest and most prestigious universities, with world-leading research and a vibrant student community.",
      websiteUrl: "https://ed.ac.uk",
      russellGroup: true,
      ranking: 5,
      entryRequirements: "AAA to ABB depending on course. Scottish students may apply through UCAS.",
      ucasPoints: null,
      studentSatisfaction: 4.2,
      notableSubjects: ["Medicine", "Law", "Informatics", "Business", "Engineering", "Social Sciences"],
      facilities: ["Old Town campus", "King's Buildings science campus", "Sports Union"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[0].id, insertedCareers[3].id, insertedCareers[8].id],
    },
    {
      name: "University of Manchester",
      type: "University",
      region: "North West",
      city: "Manchester",
      description: "A Russell Group university with outstanding research, a large student population and excellent industry links in the North West.",
      websiteUrl: "https://manchester.ac.uk",
      russellGroup: true,
      ranking: 6,
      entryRequirements: "AAB to ABB depending on course.",
      ucasPoints: null,
      studentSatisfaction: 4.1,
      notableSubjects: ["Computer Science", "Physics", "Medicine", "Business", "Law", "Engineering"],
      facilities: ["Alliance Manchester Business School", "University of Manchester Library", "Armitage Sports Centre"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[1].id, insertedCareers[5].id, insertedCareers[12].id],
    },
    {
      name: "University of Bristol",
      type: "University",
      region: "South West",
      city: "Bristol",
      description: "A leading research university in the heart of Bristol with strong STEM, arts, and social science provision.",
      websiteUrl: "https://bristol.ac.uk",
      russellGroup: true,
      ranking: 8,
      entryRequirements: "AAA to AAB depending on course.",
      ucasPoints: null,
      studentSatisfaction: 4.2,
      notableSubjects: ["Engineering", "Law", "Geography", "Medicine", "Computer Science", "Film"],
      facilities: ["Queens Building Engineering", "Student Union", "Sports facilities"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[3].id, insertedCareers[9].id, insertedCareers[2].id],
    },
    {
      name: "Leeds Beckett University",
      type: "University",
      region: "Yorkshire",
      city: "Leeds",
      description: "A modern university with strong vocational programmes in sport, business, health, and creative industries.",
      websiteUrl: "https://leedsbeckett.ac.uk",
      russellGroup: false,
      ranking: 80,
      entryRequirements: "96-120 UCAS points. Typically BBC-CCC at A-Level.",
      ucasPoints: 104,
      studentSatisfaction: 3.9,
      notableSubjects: ["Sport and Exercise Science", "Business", "Nursing", "Creative Arts", "Criminology"],
      facilities: ["Carnegie Sport facility", "School of Sport campus", "City Centre campus"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[11].id, insertedCareers[4].id, insertedCareers[7].id],
    },
    {
      name: "Birmingham City University",
      type: "University",
      region: "Midlands",
      city: "Birmingham",
      description: "A modern university focused on employability, with strong links to industry across the Midlands and beyond.",
      websiteUrl: "https://bcu.ac.uk",
      russellGroup: false,
      ranking: 92,
      entryRequirements: "96-112 UCAS points.",
      ucasPoints: 104,
      studentSatisfaction: 4.0,
      notableSubjects: ["Nursing", "Business", "Creative Arts", "Law", "Computing", "Architecture"],
      facilities: ["Millennium Point", "City South campus", "STEAMhouse"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[4].id, insertedCareers[7].id, insertedCareers[1].id],
    },
    {
      name: "Royal College of Music",
      type: "Conservatoire",
      region: "London",
      city: "London",
      description: "One of the world's great conservatoires, training professional musicians in performance, composition, and conducting.",
      websiteUrl: "https://rcm.ac.uk",
      russellGroup: false,
      ranking: null,
      entryRequirements: "Audition-based entry. Strong musical background required. Typically AAB with Music A-Level.",
      ucasPoints: null,
      studentSatisfaction: 4.6,
      notableSubjects: ["Performance", "Composition", "Conducting", "Opera", "Jazz"],
      facilities: ["Concert halls", "Practice rooms", "Recording studio", "Instrument collection"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[10].id],
    },
    {
      name: "London School of Economics",
      type: "University",
      region: "London",
      city: "London",
      description: "The world's leading dedicated social science university, renowned for economics, finance, law, and international relations.",
      websiteUrl: "https://lse.ac.uk",
      russellGroup: true,
      ranking: 4,
      entryRequirements: "A*AA to AAA. Some courses require Maths A-Level.",
      ucasPoints: null,
      studentSatisfaction: 4.1,
      notableSubjects: ["Economics", "Finance", "Law", "Sociology", "International Relations", "Statistics"],
      facilities: ["Central Library", "SU bar and clubs", "Student Services Centre"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[5].id, insertedCareers[3].id, insertedCareers[12].id],
    },
    {
      name: "Newcastle College",
      type: "College",
      region: "North East",
      city: "Newcastle",
      description: "One of the largest further education colleges in the UK, offering A-Levels, BTECs, T-Levels, apprenticeships, and Higher Education.",
      websiteUrl: "https://ncl-coll.ac.uk",
      russellGroup: false,
      ranking: null,
      entryRequirements: "GCSE grades 4-9. Varies by course.",
      ucasPoints: null,
      studentSatisfaction: 4.1,
      notableSubjects: ["Engineering", "Creative Arts", "Business", "Health and Social Care", "Computing", "Animal Care"],
      facilities: ["Industry-standard workshops", "Media studios", "Student support centre"],
      bursaries: true,
      internationalStudents: false,
      relatedCareers: [insertedCareers[2].id, insertedCareers[7].id, insertedCareers[4].id],
    },
    {
      name: "Gloucestershire College",
      type: "College",
      region: "South West",
      city: "Cheltenham",
      description: "A dynamic FE college offering vocational courses, A-Levels, T-Levels, and university-level qualifications across the Cotswolds area.",
      websiteUrl: "https://gloscol.ac.uk",
      russellGroup: false,
      ranking: null,
      entryRequirements: "GCSE grades 4+. Course-specific entry.",
      ucasPoints: null,
      studentSatisfaction: 4.0,
      notableSubjects: ["Outdoor Activities", "Sport", "Business", "Health and Social Care", "Creative Arts"],
      facilities: ["Sports hall", "Workshops", "Childcare centre"],
      bursaries: true,
      internationalStudents: false,
      relatedCareers: [insertedCareers[6].id, insertedCareers[11].id],
    },
    {
      name: "Multiverse",
      type: "Apprenticeship Provider",
      region: "London",
      city: "London",
      description: "A leading apprenticeship provider offering technology, data, and business apprenticeships with top employers across the UK.",
      websiteUrl: "https://multiverse.io",
      russellGroup: false,
      ranking: null,
      entryRequirements: "Varies by employer — generally 3 GCSEs grade 4+ including Maths and English. No prior experience needed.",
      ucasPoints: null,
      studentSatisfaction: 4.3,
      notableSubjects: ["Software Engineering", "Data Science", "Digital Marketing", "Business Administration"],
      facilities: ["Online and in-person learning", "Coaching and mentorship"],
      bursaries: false,
      internationalStudents: false,
      relatedCareers: [insertedCareers[1].id, insertedCareers[12].id, insertedCareers[5].id],
    },
    {
      name: "Goldsmiths, University of London",
      type: "University",
      region: "London",
      city: "London",
      description: "A celebrated creative arts and social sciences university known for producing leading artists, musicians, designers, and writers.",
      websiteUrl: "https://gold.ac.uk",
      russellGroup: false,
      ranking: 45,
      entryRequirements: "BBB to BBC. Portfolio required for arts courses.",
      ucasPoints: 120,
      studentSatisfaction: 4.0,
      notableSubjects: ["Fine Art", "Music", "Sociology", "Media", "Creative Writing", "Design"],
      facilities: ["Art studios", "Recording studios", "Student Union"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[7].id, insertedCareers[10].id],
    },
    {
      name: "University of Warwick",
      type: "University",
      region: "Midlands",
      city: "Coventry",
      description: "A Russell Group university known for its excellence in mathematics, sciences, business, and social sciences.",
      websiteUrl: "https://warwick.ac.uk",
      russellGroup: true,
      ranking: 10,
      entryRequirements: "AAA to ABB depending on course.",
      ucasPoints: null,
      studentSatisfaction: 4.2,
      notableSubjects: ["Mathematics", "Computer Science", "Economics", "Business", "Engineering", "Law"],
      facilities: ["Warwick Arts Centre", "Sports Hub", "Science Park"],
      bursaries: true,
      internationalStudents: true,
      relatedCareers: [insertedCareers[5].id, insertedCareers[12].id, insertedCareers[1].id],
    },
  ];

  const insertedInstitutions = await db.insert(institutionsTable).values(institutionData).returning();
  console.log(`Inserted ${insertedInstitutions.length} institutions`);

  // ─── ROUTES ─────────────────────────────────────────────────────────────────
  const routeData = [
    {
      name: "A-Levels",
      type: "Academic",
      afterLevel: "GCSE",
      duration: "2 years (Year 12 & 13)",
      description: "The traditional academic route after GCSEs, taken at school sixth form or sixth form college. You typically study 3 A-Level subjects in depth. Essential for most university courses.",
      pros: [
        "Widely recognised by universities worldwide",
        "Allows deep specialisation in subjects you enjoy",
        "Strong foundation for competitive degree programmes",
        "Well-understood grading system (A* to E)",
      ],
      cons: [
        "Narrow focus — only 3-4 subjects",
        "Heavy exam-based assessment for most subjects",
        "Not ideal for students who prefer practical learning",
        "Can feel disconnected from workplace skills",
      ],
      entryRequirements: "Typically 5 GCSEs grade 4-9, including English and Maths. Individual schools may require higher grades for specific subjects.",
      potentialEarnings: "Depends on degree/career — university graduate average starting salary £27,000-£35,000",
      examples: ["Study Biology, Chemistry, Maths → apply for Medicine or Pharmacy", "Study English, History, Politics → apply for Law or Journalism"],
    },
    {
      name: "T-Levels",
      type: "Vocational",
      afterLevel: "GCSE",
      duration: "2 years",
      description: "New technical qualifications equivalent to 3 A-Levels, combining classroom learning with a 45-day industry placement. Designed with employers to develop technical skills for specific sectors.",
      pros: [
        "Includes substantial industry placement (minimum 315 hours)",
        "Equivalent to 3 A-Levels for UCAS points",
        "Recognised by universities and employers",
        "Excellent preparation for technical careers or degree apprenticeships",
      ],
      cons: [
        "Not as widely available as A-Levels yet",
        "Not suitable for all degree programmes",
        "Less flexibility — more focused on one technical area",
      ],
      entryRequirements: "Typically 4-5 GCSEs grade 4-9. English and Maths grade 4 usually required.",
      potentialEarnings: "£25,000-£60,000 depending on sector and experience",
      examples: ["T-Level in Digital → Software Engineering apprenticeship", "T-Level in Health → Nursing degree", "T-Level in Construction → Civil Engineering"],
    },
    {
      name: "BTEC Extended Diploma",
      type: "Vocational",
      afterLevel: "GCSE",
      duration: "2 years",
      description: "A practical, portfolio-based qualification equivalent to 3 A-Levels. Assessed mainly through coursework and projects rather than exams. Excellent for hands-on learners.",
      pros: [
        "No traditional exams — coursework and project based",
        "Accepted by most universities",
        "Very practical and career-focused",
        "Encourages independent working and creativity",
      ],
      cons: [
        "Some Russell Group universities may not accept it alone",
        "Requires strong time management and self-discipline",
        "Less recognised internationally than A-Levels",
      ],
      entryRequirements: "4 GCSEs grade 3-4+, depending on the college. English and Maths often required at grade 3-4.",
      potentialEarnings: "£20,000-£55,000 depending on subject and career path",
      examples: ["BTEC Business → Marketing or HR degree", "BTEC Sport → Sports Science degree", "BTEC Art and Design → Creative Arts degree"],
    },
    {
      name: "Apprenticeship (Level 3)",
      type: "Apprenticeship",
      afterLevel: "GCSE",
      duration: "1-2 years",
      description: "Earn while you learn. Level 3 apprenticeships are equivalent to A-Levels and include on-the-job training combined with off-the-job study (typically 1 day per week at college).",
      pros: [
        "Earn a salary while training (typically £12,000-£20,000 starting)",
        "No student debt",
        "Gain real workplace experience from day one",
        "Can lead to higher or degree apprenticeships",
      ],
      cons: [
        "Competitive — employers select candidates",
        "Less academic depth than A-Levels",
        "May need to relocate depending on employer",
        "Can be demanding combining work and study",
      ],
      entryRequirements: "Varies by employer. Generally 5 GCSEs grade 4+ including English and Maths. Some employers accept lower grades.",
      potentialEarnings: "£18,000-£35,000 after completion",
      examples: ["Business Administration apprenticeship", "IT apprenticeship with BT or GCHQ", "Electrical Engineering apprenticeship"],
    },
    {
      name: "International Baccalaureate (IB)",
      type: "Academic",
      afterLevel: "GCSE",
      duration: "2 years",
      description: "A rigorous international qualification studying 6 subjects at higher or standard level, plus Theory of Knowledge, Extended Essay, and CAS (Creativity, Activity, Service). Highly regarded internationally.",
      pros: [
        "Excellent for international university applications",
        "Broader than A-Levels — 6 subjects across disciplines",
        "Develops critical thinking, research, and service skills",
        "Highly respected by world's top universities",
      ],
      cons: [
        "Very demanding — significant workload",
        "Only available at select schools",
        "Can be stressful — six subjects plus extras",
        "Less aligned to UCAS than A-Levels",
      ],
      entryRequirements: "Strong academic GCSE profile (grade 6+ across most subjects). English proficiency essential.",
      potentialEarnings: "Similar to or higher than A-Level depending on university and career path",
      examples: ["IB → Oxford, Cambridge or international universities", "IB → Global careers in international organisations"],
    },
    {
      name: "University (Undergraduate Degree)",
      type: "Academic",
      afterLevel: "A-Level",
      duration: "3-4 years (or 5-6 for medicine)",
      description: "Study a subject in depth at degree level, typically in a university. Includes lectures, seminars, practical work, and independent study. The most common route to professional careers.",
      pros: [
        "Opens doors to graduate-level careers",
        "Student loan available (repayable on income)",
        "Social and networking opportunities",
        "Develops independence and critical thinking",
        "Many part-time work opportunities alongside study",
      ],
      cons: [
        "Significant student debt (up to £27,000+ tuition in England)",
        "Takes 3+ years to complete",
        "Not all degrees have clear career paths",
        "Competition for graduate jobs is high",
      ],
      entryRequirements: "Typically 2-3 A-Levels (or equivalent UCAS points). Entry requirements vary widely — from BCC to A*A*A.",
      potentialEarnings: "Graduate starting salaries £27,000-£35,000 average; higher for medicine, law, engineering",
      examples: ["BSc Computer Science → Software Engineer", "LLB Law → Solicitor", "BSc Nursing → Registered Nurse"],
    },
    {
      name: "Degree Apprenticeship",
      type: "Apprenticeship",
      afterLevel: "A-Level",
      duration: "4-6 years",
      description: "Earn a full bachelor's or master's degree while working and earning a salary. Government and employer-funded — no student debt. Combines day-release study with full-time employment.",
      pros: [
        "Full degree with no tuition fees",
        "Earn a salary throughout (£18,000-£30,000 typically)",
        "Workplace experience from day one",
        "Often leads directly to a graduate role with the employer",
        "Rapidly growing — more routes available each year",
      ],
      cons: [
        "Competitive entry — like applying for a job and university",
        "Less campus social experience",
        "Study and work balance can be demanding",
        "Limited to sectors offering the programme",
      ],
      entryRequirements: "Usually 2-3 A-Levels or equivalent. Employer and university requirements vary significantly.",
      potentialEarnings: "£25,000-£45,000 on completion, increasing with experience",
      examples: ["Degree Apprenticeship in Software Engineering (BT, Google, KPMG)", "Degree Apprenticeship in Nursing (NHS)", "Degree Apprenticeship in Civil Engineering (Balfour Beatty)"],
    },
    {
      name: "Higher Apprenticeship (Level 4/5)",
      type: "Apprenticeship",
      afterLevel: "A-Level",
      duration: "1-3 years",
      description: "Earn a Higher National Certificate (HNC) or Higher National Diploma (HND) — equivalent to the first or second year of a degree — while working.",
      pros: [
        "No tuition fees",
        "Earn while you learn",
        "Can progress to a degree apprenticeship or top-up degree",
        "Highly practical and employer-focused",
      ],
      cons: [
        "Not a full degree on its own",
        "Less recognition than a bachelor's degree in some fields",
        "Competitive entry",
      ],
      entryRequirements: "A-Levels or equivalent. Some employers accept BTEC or strong GCSE results.",
      potentialEarnings: "£22,000-£40,000 on completion",
      examples: ["HNC Engineering (Rolls-Royce)", "Higher Apprenticeship in Accounting (PwC School Leaver)", "Higher Apprenticeship in IT"],
    },
    {
      name: "School Leaver Professional Programme",
      type: "School Leaver",
      afterLevel: "A-Level",
      duration: "3-6 years",
      description: "Structured graduate-equivalent programmes at top firms (law, finance, consulting, accounting) that accept A-Level students directly, bypassing university.",
      pros: [
        "Enter professional careers straight from school",
        "No student debt",
        "Often leads to professional qualifications (ACA, ACCA, LPC)",
        "Competitive salaries and rapid progression",
      ],
      cons: [
        "Very competitive — Oxbridge-level application process",
        "Miss out on university social experience",
        "Requires very strong A-Level results",
        "Long programmes with demanding workload",
      ],
      entryRequirements: "Strong A-Level results (ABB-AAA). GCSE Maths and English grade 6+. Competitive assessment centres.",
      potentialEarnings: "£25,000-£40,000 starting, rising quickly",
      examples: ["PwC School Leavers (accounting/consulting)", "Clifford Chance A-Level scheme (law)", "KPMG School Leaver programme"],
    },
    {
      name: "Foundation Degree",
      type: "Academic",
      afterLevel: "A-Level",
      duration: "2 years",
      description: "A vocational higher education qualification at Level 5 — equivalent to the first two years of a bachelor's degree. Offered at universities and colleges, often with the option to top up to a full degree.",
      pros: [
        "Shorter than a full degree",
        "Practical and career-focused",
        "Can top up to a full bachelor's degree in 1 year",
        "Lower entry requirements than a full degree",
      ],
      cons: [
        "Not a full degree without top-up",
        "Less recognised in some professional fields",
        "Limited range of subjects compared to full degrees",
      ],
      entryRequirements: "Typically 40-80 UCAS points. 1-2 A-Levels or BTEC diploma.",
      potentialEarnings: "£20,000-£40,000 depending on field",
      examples: ["FdSc Health and Social Care", "FdA Creative Media Production", "FdEng Engineering"],
    },
    {
      name: "Gap Year",
      type: "Gap Year",
      afterLevel: "A-Level",
      duration: "1 year",
      description: "Take a structured year out before higher education or employment to travel, volunteer, work, or develop skills. Deferred university entry is common.",
      pros: [
        "Personal development and life experience",
        "Can strengthen UCAS or job applications",
        "Opportunity to explore career options",
        "Time to earn and save money",
      ],
      cons: [
        "No guaranteed structure — requires discipline",
        "Can delay earning a degree or entering career",
        "Not all employers view it positively",
      ],
      entryRequirements: "No formal entry requirements. Planning and funding required.",
      potentialEarnings: "Varies — volunteering (unpaid) to travel and work abroad programmes",
      examples: ["Raleigh International volunteer programme", "Working Holiday Visa (Australia/NZ)", "Teaching English abroad (TEFL)"],
    },
  ];

  const insertedRoutes = await db.insert(routesTable).values(routeData).returning();
  console.log(`Inserted ${insertedRoutes.length} routes`);

  console.log("Seeding complete!");
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
